// ── TOPIK I ──────────────────────────────────────────────────────────────────

export const topikIGrammar = [
  {
    category: 'Sentence Structure',
    gameCategory: 'TopicMarker',
    color: 'purple',
    rules: [
      {
        title: 'SOV Word Order',
        gameCategory: 'TopicMarker',
        pattern: 'Subject + Object + Verb',
        example: '저는 사과를 먹어요.',
        translation: 'I eat an apple.',
        note: 'Korean always puts the verb at the end of the sentence.',
      },
      {
        title: 'Topic vs. Subject',
        gameCategory: 'TopicMarker',
        pattern: 'Topic: 은/는 · Subject: 이/가',
        example: '저는 학생이에요. 제가 해요.',
        translation: 'I am a student. (It is) I who does it.',
        note: '은/는 marks the topic (what we are talking about); 이/가 marks the grammatical subject.',
      },
    ],
  },
  {
    category: 'Particles (조사)',
    gameCategory: 'TopicMarker',
    color: 'blue',
    rules: [
      {
        title: 'Topic marker 은/는',
        gameCategory: 'TopicMarker',
        pattern: 'Noun(consonant) + 은 · Noun(vowel) + 는',
        example: '저는 한국어를 공부해요.',
        translation: 'I study Korean.',
        note: '은 after a consonant, 는 after a vowel.',
      },
      {
        title: 'Subject marker 이/가',
        gameCategory: 'SubjectMarker',
        pattern: 'Noun(consonant) + 이 · Noun(vowel) + 가',
        example: '고양이가 귀여워요.',
        translation: 'The cat is cute.',
        note: '이 after a consonant, 가 after a vowel.',
      },
      {
        title: 'Object marker 을/를',
        gameCategory: 'ObjectMarker',
        pattern: 'Noun(consonant) + 을 · Noun(vowel) + 를',
        example: '물을 마셔요.',
        translation: 'I drink water.',
        note: '을 after a consonant, 를 after a vowel.',
      },
      {
        title: 'Location 에 vs 에서',
        gameCategory: 'LocationParticle',
        pattern: '에 = place of existence/direction · 에서 = place of action',
        example: '학교에 가요. 학교에서 공부해요.',
        translation: 'I go to school. I study at school.',
        note: '에 is used with 있다/없다 and movement verbs; 에서 is used with action verbs.',
      },
      {
        title: 'Possessive marker 의',
        gameCategory: 'PossessiveMarker',
        pattern: 'Noun + 의 + Noun',
        example: '제 친구의 책이에요.',
        translation: "It is my friend's book.",
        note: '의 is often dropped in casual speech.',
      },
      {
        title: 'Direction/Means 으로/로',
        gameCategory: 'LocationParticle',
        pattern: 'Noun(consonant except ㄹ) + 으로 · Noun(vowel or ㄹ) + 로',
        example: '왼쪽으로 가세요. 버스로 가요.',
        translation: 'Go to the left. I go by bus.',
        note: 'Used for direction, means of transport, or tool.',
      },
      {
        title: 'With/And 와/과, 하고',
        gameCategory: 'ConjParticle',
        pattern: 'Noun(vowel) + 와 · Noun(consonant) + 과 · Noun + 하고 (casual)',
        example: '친구와 영화를 봐요.',
        translation: 'I watch a movie with a friend.',
        note: '하고 is more common in spoken Korean.',
      },
    ],
  },
  {
    category: 'Verb Conjugation',
    gameCategory: 'Verb Form',
    color: 'green',
    rules: [
      {
        title: 'Present tense -아요/어요',
        pattern: 'Stem(아/오 vowel) + 아요 · Stem(other) + 어요',
        example: '먹어요. 가요. 해요.',
        translation: 'Eat. Go. Do.',
        note: '하다 verbs → 해요. Stems ending in ㅏ/ㅗ take 아요, all others take 어요.',
      },
      {
        title: 'Past tense -았어요/었어요',
        pattern: 'Stem(아/오) + 았어요 · Stem(other) + 었어요',
        example: '먹었어요. 갔어요. 했어요.',
        translation: 'Ate. Went. Did.',
        note: '하다 verbs → 했어요.',
      },
      {
        title: 'Future -(으)ㄹ 거예요',
        pattern: 'Stem(consonant) + 을 거예요 · Stem(vowel) + ㄹ 거예요',
        example: '먹을 거예요. 갈 거예요.',
        translation: 'I will eat. I will go.',
        note: 'Expresses future plans or intentions.',
      },
      {
        title: 'Intention -(으)려고 해요',
        pattern: 'Stem(consonant) + 으려고 해요 · Stem(vowel) + 려고 해요',
        example: '공부하려고 해요.',
        translation: 'I am planning to study.',
        note: 'Expresses a plan or intention.',
      },
      {
        title: 'Progressive -고 있어요',
        pattern: 'Verb stem + 고 있어요',
        example: '밥을 먹고 있어요.',
        translation: 'I am eating.',
        note: 'Equivalent to the English "-ing" form.',
      },
    ],
  },
  {
    category: 'Negative Forms',
    gameCategory: 'Negation',
    color: 'red',
    rules: [
      {
        title: 'Short negation 안',
        pattern: '안 + Verb/Adjective',
        example: '안 먹어요. 안 가요.',
        translation: "I don't eat. I don't go.",
        note: "안 is placed directly before the verb. Not used with 하다 → 하다 → 안 해요.",
      },
      {
        title: 'Long negation -지 않아요',
        pattern: 'Verb stem + 지 않아요',
        example: '먹지 않아요.',
        translation: 'I do not eat.',
        note: 'More formal than 안. Works with all verbs.',
      },
      {
        title: 'Cannot -지 못해요 / 못',
        pattern: '못 + Verb · Verb stem + 지 못해요',
        example: '못 가요. 가지 못해요.',
        translation: "I can't go.",
        note: 'Expresses inability (not a choice, but a limitation).',
      },
      {
        title: 'Not exist 없어요',
        pattern: 'Noun + 이/가 없어요',
        example: '시간이 없어요.',
        translation: "There is no time. / I don't have time.",
        note: 'Opposite of 있어요.',
      },
    ],
  },
  {
    category: 'Connectives',
    gameCategory: 'Connectives',
    color: 'yellow',
    rules: [
      {
        title: 'And (actions) -고',
        pattern: 'Verb stem + 고',
        example: '밥을 먹고 학교에 가요.',
        translation: 'I eat and (then) go to school.',
        note: 'Connects two sequential or simultaneous actions.',
      },
      {
        title: 'But -지만',
        pattern: 'Verb/Adj stem + 지만',
        example: '비싸지만 맛있어요.',
        translation: 'It is expensive but delicious.',
        note: 'Contrasts two clauses.',
      },
      {
        title: 'If -(으)면',
        pattern: 'Stem(consonant) + 으면 · Stem(vowel/ㄹ) + 면',
        example: '시간이 있으면 와요.',
        translation: 'If you have time, come.',
        note: 'Used for conditions.',
      },
      {
        title: 'Because -아서/어서',
        pattern: 'Stem(아/오) + 아서 · Stem(other) + 어서',
        example: '배가 고파서 먹어요.',
        translation: 'I eat because I am hungry.',
        note: 'Cannot be used with past/future tense endings.',
      },
      {
        title: 'Because -(으)니까',
        pattern: 'Stem(consonant) + 으니까 · Stem(vowel) + 니까',
        example: '늦으니까 빨리 가요.',
        translation: "Since it's late, hurry.",
        note: 'Can combine with past tense; often used for commands/suggestions.',
      },
      {
        title: 'When -(으)ㄹ 때',
        pattern: 'Verb/Adj stem + (으)ㄹ 때',
        example: '어릴 때 한국에 살았어요.',
        translation: 'When I was young, I lived in Korea.',
        note: 'Expresses "when/at the time of".',
      },
    ],
  },
  {
    category: 'Copula & Existence',
    gameCategory: 'Copula',
    color: 'pink',
    rules: [
      {
        title: 'To be 이에요/예요',
        pattern: 'Noun(consonant) + 이에요 · Noun(vowel) + 예요',
        example: '저는 학생이에요. 저는 의사예요.',
        translation: 'I am a student. I am a doctor.',
        note: 'Polite form of 이다.',
      },
      {
        title: 'Not to be 이/가 아니에요',
        pattern: 'Noun + 이/가 아니에요',
        example: '저는 학생이 아니에요.',
        translation: 'I am not a student.',
        note: 'Negative form of 이다.',
      },
      {
        title: 'Exist/Have 있어요',
        pattern: 'Noun + 이/가 있어요',
        example: '책이 있어요. 시간이 있어요?',
        translation: 'There is a book. / Do you have time?',
        note: 'Used for existence and possession.',
      },
      {
        title: "Not exist/Don't have 없어요",
        pattern: 'Noun + 이/가 없어요',
        example: '돈이 없어요.',
        translation: "There is no money. / I don't have money.",
        note: 'Opposite of 있어요.',
      },
    ],
  },
  {
    category: 'Requests & Suggestions',
    gameCategory: 'Patterns',
    color: 'orange',
    rules: [
      {
        title: 'Please do -(으)세요',
        pattern: 'Stem(consonant) + 으세요 · Stem(vowel/ㄹ) + 세요',
        example: '앉으세요. 드세요.',
        translation: 'Please sit. Please eat.',
        note: 'Polite request or honorific present tense.',
      },
      {
        title: "Let's -아요/어요 (suggestion)",
        pattern: 'Same as present tense',
        example: '같이 가요!',
        translation: "Let's go together!",
        note: 'The same -아요/어요 form is used for suggestions depending on context.',
      },
      {
        title: 'Want to -고 싶어요',
        pattern: 'Verb stem + 고 싶어요',
        example: '한국에 가고 싶어요.',
        translation: 'I want to go to Korea.',
        note: 'Expresses a desire.',
      },
      {
        title: 'Can/Able to -(으)ㄹ 수 있어요',
        pattern: 'Stem(consonant) + 을 수 있어요 · Stem(vowel) + ㄹ 수 있어요',
        example: '한국어를 할 수 있어요.',
        translation: 'I can speak Korean.',
        note: 'Negate with -(으)ㄹ 수 없어요 or 없다.',
      },
    ],
  },
  {
    category: 'Numbers & Counters',
    gameCategory: 'Numbers',
    color: 'teal',
    rules: [
      {
        title: 'Sino-Korean numbers (일, 이, 삼…)',
        pattern: '일(1) 이(2) 삼(3) 사(4) 오(5) 육(6) 칠(7) 팔(8) 구(9) 십(10)',
        example: '십오 분, 삼월, 오백 원',
        translation: '15 minutes, March, 500 won',
        note: 'Used for dates, money, minutes, phone numbers.',
      },
      {
        title: 'Native Korean numbers (하나, 둘, 셋…)',
        pattern: '하나(1) 둘(2) 셋(3) 넷(4) 다섯(5) 여섯(6) 일곱(7) 여덟(8) 아홉(9) 열(10)',
        example: '사람 두 명, 사과 세 개',
        translation: 'Two people, three apples',
        note: '하나→한, 둘→두, 셋→세, 넷→네 before counters.',
      },
      {
        title: 'Common counters',
        pattern: '개 (objects) · 명 (people) · 권 (books) · 잔 (drinks) · 번 (times)',
        example: '커피 두 잔, 책 한 권, 세 번',
        translation: 'Two coffees, one book, three times',
        note: 'Counter follows the number.',
      },
    ],
  },
]

// ── TOPIK II ─────────────────────────────────────────────────────────────────

export const topikIIGrammar = [
  {
    category: 'Modal Expressions',
    gameCategory: 'Modals',
    color: 'indigo',
    rules: [
      {
        title: 'Must / Have to -아야/어야 해요',
        pattern: 'Stem(아/오) + 아야 해요 · Stem(other) + 어야 해요',
        example: '숙제를 해야 해요. 약을 먹어야 해요.',
        translation: 'I have to do homework. I must take medicine.',
        note: '-아야 돼요 is equally correct. Both mean "must/have to".',
      },
      {
        title: 'May / Okay to -아/어도 돼요',
        pattern: 'Stem(아/오) + 아도 돼요 · Stem(other) + 어도 돼요',
        example: '여기서 사진을 찍어도 돼요?',
        translation: 'May I take photos here?',
        note: 'Asks or grants permission. Also: -(아/어)도 괜찮아요.',
      },
      {
        title: 'Must not -면 안 돼요',
        pattern: 'Verb stem + 면 안 돼요',
        example: '담배를 피우면 안 돼요.',
        translation: 'You must not smoke.',
        note: 'Expresses prohibition. Literally "if you do X, it won\'t do".',
      },
      {
        title: 'Promise / Voluntary intention -ㄹ게요',
        pattern: 'Stem(consonant) + 을게요 · Stem(vowel/ㄹ) + ㄹ게요',
        example: '제가 할게요. 내일 올게요.',
        translation: 'I will do it. I will come tomorrow.',
        note: 'Only used when the speaker is the subject. Conveys a promise or decision.',
      },
    ],
  },
  {
    category: 'Indirect Speech',
    gameCategory: 'Indirect',
    color: 'violet',
    rules: [
      {
        title: 'Indirect statement -(ㄴ/는)다고 해요',
        pattern: 'Action verb -는다고 해요 · Adj/copula -(으)ㄴ다고 해요',
        example: '친구가 한국에 간다고 해요.',
        translation: 'My friend says (that) they are going to Korea.',
        note: 'Reports what someone said. Contracted: -대요.',
      },
      {
        title: 'Indirect question -(느)냐고 해요',
        pattern: 'Action verb -느냐고 해요 · Adj -(으)냐고 해요',
        example: '어디 가느냐고 물었어요.',
        translation: 'They asked where I was going.',
        note: 'Reports a question. Contracted: -냬요.',
      },
      {
        title: 'Indirect command -(으)라고 해요',
        pattern: 'Stem(consonant) + 으라고 해요 · Stem(vowel/ㄹ) + 라고 해요',
        example: '선생님이 공부하라고 했어요.',
        translation: 'The teacher told me to study.',
        note: 'Reports a command or order.',
      },
      {
        title: 'Indirect suggestion -자고 해요',
        pattern: 'Verb stem + 자고 해요',
        example: '같이 밥 먹자고 했어요.',
        translation: "They suggested eating together.",
        note: "Reports a suggestion (let's...). Contracted: -재요.",
      },
    ],
  },
  {
    category: 'Passive & Causative',
    gameCategory: 'Passive',
    color: 'rose',
    rules: [
      {
        title: 'Suffix passives -이/히/리/기',
        pattern: 'Verb stem + 이/히/리/기 (fixed per verb)',
        example: '문이 열려요. 도둑이 잡혔어요.',
        translation: 'The door opens/is opened. The thief was caught.',
        note: 'Common passives: 보이다, 들리다, 닫히다, 잡히다, 먹히다, 열리다.',
      },
      {
        title: 'Become / Get -아/어지다',
        pattern: 'Adjective stem + 아/어지다',
        example: '날씨가 따뜻해졌어요. 한국어가 쉬워졌어요.',
        translation: 'The weather got warmer. Korean got easier.',
        note: 'Attaches to adjectives to express a change of state.',
      },
      {
        title: 'Causative -이/히/리/기/우/추',
        pattern: 'Verb stem + causative suffix (fixed per verb)',
        example: '아이에게 밥을 먹였어요. 아이를 울렸어요.',
        translation: 'I fed the child. I made the child cry.',
        note: 'Examples: 먹이다, 입히다, 울리다, 앉히다, 세우다. Each verb has a fixed suffix.',
      },
    ],
  },
  {
    category: 'Advanced Connectives',
    gameCategory: 'AdvConnectives',
    color: 'amber',
    rules: [
      {
        title: 'While / At the same time -면서',
        pattern: 'Verb stem + 면서',
        example: '음악을 들으면서 공부해요.',
        translation: 'I study while listening to music.',
        note: 'Both actions happen simultaneously, with the same subject.',
      },
      {
        title: 'Even if / Even though -아/어도',
        pattern: 'Stem(아/오) + 아도 · Stem(other) + 어도',
        example: '바빠도 운동해요. 비가 와도 가요.',
        translation: "Even if I'm busy, I exercise. Even if it rains, I go.",
        note: "The result doesn't change regardless of the condition.",
      },
      {
        title: 'The more -(으)ㄹ수록',
        pattern: '-(으)면 -(으)ㄹ수록 (optional 면)',
        example: '공부할수록 한국어가 재미있어요.',
        translation: 'The more I study, the more interesting Korean gets.',
        note: 'Often paired with -면: 먹으면 먹을수록 (the more I eat...).',
      },
      {
        title: 'Background / Contrast -ㄴ/는데',
        pattern: 'Action stem + 는데 · Adj(consonant) + 은데 · Adj(vowel) + ㄴ데',
        example: '비가 오는데 우산이 없어요.',
        translation: "It's raining but I don't have an umbrella.",
        note: '-는데/ㄴ데 provides background context or a soft contrast.',
      },
    ],
  },
  {
    category: 'Noun Modifiers',
    gameCategory: 'Modifiers',
    color: 'sky',
    rules: [
      {
        title: 'Past modifier -(으)ㄴ + Noun',
        pattern: 'Action verb(consonant) + 은 · Action verb(vowel/ㄹ) + ㄴ + Noun',
        example: '제가 먹은 음식이에요. 어제 만난 사람이에요.',
        translation: "It's the food I ate. It's the person I met yesterday.",
        note: 'Describes a completed action modifying a noun (relative clause).',
      },
      {
        title: 'Present modifier -는 + Noun',
        pattern: 'Action verb stem + 는 + Noun',
        example: '지금 먹는 음식이에요. 한국어를 공부하는 학생이에요.',
        translation: "It's food I'm eating now. She's a student studying Korean.",
        note: 'Action verbs use -는 for present. Adjectives use -(으)ㄴ for current state.',
      },
      {
        title: 'Future modifier -(으)ㄹ + Noun',
        pattern: 'Stem(consonant) + 을 · Stem(vowel/ㄹ) + ㄹ + Noun',
        example: '내일 먹을 음식이에요. 갈 곳이 없어요.',
        translation: "It's food I will eat tomorrow. There's nowhere to go.",
        note: 'Describes a future or potential action modifying a noun.',
      },
      {
        title: 'Experience -(으)ㄴ 적이 있다/없다',
        pattern: 'Past modifier + 적이 있어요/없어요',
        example: '한국에 가 본 적이 있어요? 스키를 탄 적이 없어요.',
        translation: "Have you ever been to Korea? I've never skied.",
        note: 'Expresses whether one has ever experienced something.',
      },
    ],
  },
  {
    category: 'Inference & Appearance',
    gameCategory: 'Inference',
    color: 'emerald',
    rules: [
      {
        title: 'Seems like -(으)ㄴ/는 것 같아요',
        pattern: 'Adj -(으)ㄴ 것 같아요 · Action -는 것 같아요',
        example: '피곤한 것 같아요. 비가 오는 것 같아요.',
        translation: "Seems like they're tired. It seems like it's raining.",
        note: 'Expresses inference or assumption based on observation.',
      },
      {
        title: 'Will probably -(으)ㄹ 것 같아요',
        pattern: 'Stem(consonant) + 을 것 같아요 · Stem(vowel/ㄹ) + ㄹ 것 같아요',
        example: '내일 비가 올 것 같아요.',
        translation: 'It seems like it will rain tomorrow.',
        note: 'Expresses conjecture about the future.',
      },
      {
        title: 'Retrospective discovery -더라고요',
        pattern: 'Verb/Adj stem + 더라고요',
        example: '한국 음식이 정말 맛있더라고요.',
        translation: 'I found that Korean food was really delicious.',
        note: 'Reports something personally witnessed/discovered. Cannot describe yourself.',
      },
      {
        title: 'Volition / Conjecture -겠-',
        pattern: 'Verb/Adj stem + 겠 + ending',
        example: '알겠어요. 맛있겠다! 제가 하겠습니다.',
        translation: 'I understand. That looks delicious! I will do it.',
        note: 'Expresses will, polite conjecture, or hedged speech. Very common in formal settings.',
      },
    ],
  },
  {
    category: 'Formal Speech (격식체)',
    gameCategory: 'Formal',
    color: 'slate',
    rules: [
      {
        title: 'Formal statement -(스)ㅂ니다',
        pattern: 'Stem(consonant) + 습니다 · Stem(vowel/ㄹ) + ㅂ니다',
        example: '저는 학생입니다. 한국어를 공부합니다.',
        translation: 'I am a student. I study Korean.',
        note: 'Formal polite speech (합쇼체). Used in presentations, news, and formal writing.',
      },
      {
        title: 'Formal question -(스)ㅂ니까?',
        pattern: 'Stem(consonant) + 습니까? · Stem(vowel/ㄹ) + ㅂ니까?',
        example: '어디에 가십니까? 이해하셨습니까?',
        translation: 'Where are you going? Did you understand?',
        note: 'Often combined with -(으)시- for additional politeness.',
      },
      {
        title: 'Formal command -십시오',
        pattern: 'Stem(consonant) + 으십시오 · Stem(vowel/ㄹ) + 십시오',
        example: '앉으십시오. 주목해 주십시오.',
        translation: 'Please sit down. Please pay attention.',
        note: 'Used in announcements, military, and customer service contexts.',
      },
    ],
  },
  {
    category: 'Honorifics (존댓말)',
    gameCategory: 'Honorifics',
    color: 'teal',
    rules: [
      {
        title: 'Subject honorific -(으)시-',
        pattern: 'Stem(consonant) + 으시 · Stem(vowel/ㄹ) + 시 + ending',
        example: '선생님이 오세요. 할아버지가 주무세요.',
        translation: 'The teacher is coming. Grandfather is sleeping.',
        note: '-시- is inserted between the stem and ending to honor the subject.',
      },
      {
        title: 'Special honorific verbs',
        pattern: 'Replace regular verb with honorific equivalent',
        example: '드시다(eat), 주무시다(sleep), 계시다(be/stay), 돌아가시다(pass away)',
        translation: 'Honorific: eat, sleep, be present, pass away',
        note: 'These replace 먹다, 자다, 있다, 죽다 when the subject deserves respect.',
      },
      {
        title: 'Giving to a superior 드리다',
        pattern: 'Replace 주다 with 드리다 when giving TO someone respected',
        example: '선물을 드렸어요. 말씀 드릴게요.',
        translation: 'I gave (them) a gift. I will tell you.',
        note: '드리다 = give (to superior). 주다 = give (neutral). 주시다 = they give (to you, with honor).',
      },
      {
        title: 'Honorific nouns',
        pattern: "Use special nouns for a respected person's things",
        example: '댁(home), 성함(name), 연세(age), 말씀(words)',
        translation: 'Honorific: home, name, age, speech',
        note: '집→댁, 이름→성함, 나이→연세, 말→말씀 when talking about a respected person.',
      },
    ],
  },
]

// ── TOPIK I game questions ────────────────────────────────────────────────────

export const topikIGrammarQuestions = [
  // Verb Form
  { category: 'Verb Form', question: 'What is the polite present tense of 먹다 (to eat)?', answer: '먹어요', options: ['먹어요', '먹었어요', '먹을 거예요', '먹고 있어요'], explanation: '먹다 → stem 먹 → vowel ㅓ (not ㅏ/ㅗ) → add 어요 → 먹어요.' },
  { category: 'Verb Form', question: 'What is the polite present tense of 가다 (to go)?', answer: '가요', options: ['가요', '갔어요', '갈 거예요', '가서요'], explanation: '가다 → stem 가 → vowel ㅏ → add 아요, but 가 + 아요 contracts to 가요.' },
  { category: 'Verb Form', question: 'What is the polite past tense of 먹다 (to eat)?', answer: '먹었어요', options: ['먹었어요', '먹어요', '먹을 거예요', '먹었습니다'], explanation: 'Stem 먹 + 었어요 (non-ㅏ/ㅗ past suffix) = 먹었어요.' },
  { category: 'Verb Form', question: 'What is the polite past tense of 가다 (to go)?', answer: '갔어요', options: ['갔어요', '가요', '갈 거예요', '가았어요'], explanation: '가다 → 가 + 았어요 → contracts to 갔어요.' },
  { category: 'Verb Form', question: 'How do you say "I will eat" (future intention)?', answer: '먹을 거예요', options: ['먹을 거예요', '먹어요', '먹었어요', '먹고 싶어요'], explanation: 'Stem 먹 (ends in consonant) + 을 거예요 = 먹을 거예요.' },
  { category: 'Verb Form', question: 'How do you say "I am eating" (progressive)?', answer: '먹고 있어요', options: ['먹고 있어요', '먹어요', '먹었어요', '먹을 거예요'], explanation: 'Verb stem + 고 있어요 expresses ongoing action, like English "-ing".' },
  { category: 'Verb Form', question: 'What is the correct polite present of 하다 (to do)?', answer: '해요', options: ['해요', '하어요', '하요', '했어요'], explanation: '하다 is irregular: 하 + 여요 → 해요 (contraction).' },
  // Negation
  { category: 'Negation', question: "How do you say \"I don't go\" using short negation?", answer: '안 가요', options: ['안 가요', '못 가요', '가지 않아요', '가지 못해요'], explanation: "안 + verb = short negation (choice not to do). 안 가요 = I don't go." },
  { category: 'Negation', question: "What is the difference between 안 가요 and 못 가요?", answer: "안 = won't (choice), 못 = can't (inability)", options: ["안 = won't (choice), 못 = can't (inability)", '안 = past, 못 = future', '안 = formal, 못 = informal', 'They mean the same thing'], explanation: '안 expresses a deliberate choice not to do something. 못 expresses inability.' },
  { category: 'Negation', question: "How do you say \"There is no time\" / \"I don't have time\"?", answer: '시간이 없어요', options: ['시간이 없어요', '시간이 안 있어요', '시간이 못해요', '시간은 아니에요'], explanation: '없어요 (to not exist / not have) is the correct negation of 있어요.' },
  // Connectives
  { category: 'Connectives', question: '"비싸___ 맛있어요." (expensive but delicious)', answer: '지만', options: ['지만', '고', '서', '면'], explanation: '-지만 connects two contrasting ideas. 비싸다 → 비싸지만 (but).' },
  { category: 'Connectives', question: '"밥을 먹___ 학교에 가요." (eat and then go to school)', answer: '고', options: ['고', '서', '지만', '면'], explanation: '-고 connects sequential or simultaneous actions. 먹다 → 먹고.' },
  { category: 'Connectives', question: '"배가 고파___ 먹었어요." (ate because hungry)', answer: '서', options: ['서', '고', '지만', '니까'], explanation: '-아서/어서 expresses reason/cause. 고프다 → 고파서.' },
  { category: 'Connectives', question: '"시간이 있___ 와요." (if you have time, come)', answer: '으면', options: ['으면', '고', '서', '지만'], explanation: '-(으)면 = "if/when". 있다 → consonant stem → 있으면.' },
  // TopicMarker (은/는)
  { category: 'TopicMarker', question: 'Fill in: "저___ 학생이에요." (I am a student)', answer: '는', options: ['는', '이', '를', '가'], explanation: '저 ends in a vowel → topic marker 는. 저는 = "As for me, I am a student."' },
  { category: 'TopicMarker', question: 'Fill in: "책___ 재미있어요." (The book is interesting)', answer: '은', options: ['은', '는', '가', '이'], explanation: '책 ends in consonant ㄱ → topic marker 은. 책은 = "As for the book, it is interesting."' },
  { category: 'TopicMarker', question: 'When do you use 은 vs 는?', answer: '은 after a consonant, 는 after a vowel', options: ['은 after a consonant, 는 after a vowel', '는 after a consonant, 은 after a vowel', 'Use 은 always', 'Use 는 always'], explanation: '은 follows nouns ending in a consonant. 는 follows nouns ending in a vowel. E.g. 책은, 저는.' },
  // SubjectMarker (이/가)
  { category: 'SubjectMarker', question: 'Fill in: "고양이___ 귀여워요." (The cat is cute)', answer: '가', options: ['가', '이', '는', '를'], explanation: '고양이 ends in a vowel → subject marker 가. 고양이가 = the cat (subject).' },
  { category: 'SubjectMarker', question: 'Fill in: "학생___ 공부해요." (The student studies)', answer: '이', options: ['이', '가', '은', '를'], explanation: '학생 ends in consonant ㅇ → subject marker 이. 학생이 = the student (subject).' },
  { category: 'SubjectMarker', question: 'What is the difference between 이/가 and 은/는?', answer: '이/가 marks the grammatical subject; 은/는 marks the topic of discussion', options: ['이/가 marks the grammatical subject; 은/는 marks the topic of discussion', '이/가 marks the object; 은/는 marks the subject', 'They are interchangeable', '이/가 is formal; 은/는 is casual'], explanation: '이/가 identifies WHO does the action (subject). 은/는 sets the topic ("as for X"). Compare: 제가 해요 (I am the one doing it) vs 저는 학생이에요 (As for me, I am a student).' },
  // ObjectMarker (을/를)
  { category: 'ObjectMarker', question: 'Fill in: "물___ 마셔요." (I drink water)', answer: '을', options: ['을', '를', '은', '이'], explanation: '물 ends in consonant ㄹ → object marker 을. 물을 = water (direct object).' },
  { category: 'ObjectMarker', question: 'Fill in: "커피___ 마셔요." (I drink coffee)', answer: '를', options: ['를', '을', '는', '가'], explanation: '커피 ends in a vowel → object marker 를. 커피를 = coffee (direct object).' },
  { category: 'ObjectMarker', question: 'When do you use 을 vs 를?', answer: '을 after a consonant, 를 after a vowel', options: ['을 after a consonant, 를 after a vowel', '를 after a consonant, 을 after a vowel', 'Use 을 always', 'Use 를 always'], explanation: '을 follows nouns ending in a consonant. 를 follows nouns ending in a vowel. 을/를 marks the direct object of an action verb.' },
  // LocationParticle (에/에서/으로/로)
  { category: 'LocationParticle', question: '"학교___ 공부해요." (I study AT school — action)', answer: '에서', options: ['에서', '에', '으로', '와'], explanation: '에서 marks the place where an action happens. 에 is for existence or direction.' },
  { category: 'LocationParticle', question: '"학교___ 가요." (I go TO school)', answer: '에', options: ['에', '에서', '으로', '가'], explanation: '에 marks direction/destination with movement verbs like 가다, 오다.' },
  { category: 'LocationParticle', question: '"버스___ 학교에 가요." (I go to school BY bus)', answer: '로', options: ['로', '에서', '에', '을'], explanation: '으로/로 marks means of transport. 버스 ends in a vowel → 로.' },
  { category: 'LocationParticle', question: 'What is the difference between 에 and 에서?', answer: '에 = place of existence or destination; 에서 = place of action', options: ['에 = place of existence or destination; 에서 = place of action', '에서 = place of existence; 에 = place of action', 'They mean the same thing', '에 is casual; 에서 is formal'], explanation: '에 is used with 있다/없다 and movement verbs (destination). 에서 is used with action verbs (location of activity). E.g., 학교에 가요 (go TO school) vs 학교에서 공부해요 (study AT school).' },
  // PossessiveMarker (의)
  { category: 'PossessiveMarker', question: 'How do you say "my friend\'s book"?', answer: '친구의 책', options: ['친구의 책', '친구가 책', '친구를 책', '친구에서 책'], explanation: 'Possessive: Noun + 의 + Noun. 친구의 책 = friend\'s book. Note: 의 is often omitted in casual speech → 친구 책.' },
  { category: 'PossessiveMarker', question: 'What does 의 indicate in Korean?', answer: 'Possession — equivalent to "\'s" or "of" in English', options: ["Possession — equivalent to \"'s\" or \"of\" in English", 'Subject marker', 'Object marker', 'Location marker'], explanation: '의 marks possession. 선생님의 책 = "teacher\'s book". In casual speech, 의 is often dropped: 선생님 책.' },
  // ConjParticle (와/과/하고)
  { category: 'ConjParticle', question: '"친구___ 영화를 봐요." (I watch a movie WITH a friend)', answer: '와', options: ['와', '과', '에서', '를'], explanation: '친구 ends in a vowel → 와 (with/and). 과 is used after consonants. 하고 is the casual alternative for both.' },
  { category: 'ConjParticle', question: 'How do you casually say "coffee and milk"?', answer: '커피하고 우유', options: ['커피하고 우유', '커피와 우유', '커피과 우유', '커피고 우유'], explanation: '하고 is the casual, spoken form of "and/with". 와 (after vowel) and 과 (after consonant) are slightly more formal.' },
  { category: 'Patterns', question: 'How do you say "I want to go to Korea"?', answer: '한국에 가고 싶어요', options: ['한국에 가고 싶어요', '한국에 갈 거예요', '한국에 가서 싶어요', '한국에 가면 싶어요'], explanation: 'Verb stem + 고 싶어요 = want to do. 가다 → 가고 싶어요.' },
  { category: 'Patterns', question: 'How do you say "I can speak Korean"?', answer: '한국어를 할 수 있어요', options: ['한국어를 할 수 있어요', '한국어를 하고 싶어요', '한국어를 해서 있어요', '한국어를 할 거예요'], explanation: 'Verb stem + (으)ㄹ 수 있어요 = can / able to. 하다 → 할 수 있어요.' },
  { category: 'Patterns', question: 'How do you say "I am planning to study"?', answer: '공부하려고 해요', options: ['공부하려고 해요', '공부할 거예요', '공부하고 싶어요', '공부하면 해요'], explanation: 'Verb stem + (으)려고 해요 = plan/intend to. 공부하다 → 공부하려고 해요.' },
  { category: 'Patterns', question: 'How do you politely say "Please sit down"?', answer: '앉으세요', options: ['앉으세요', '앉아요', '앉고 싶어요', '앉을 거예요'], explanation: '-(으)세요 is a polite request/command form. 앉다 (consonant) → 앉으세요.' },
  { category: 'Copula', question: 'How do you say "I am not a student"?', answer: '저는 학생이 아니에요', options: ['저는 학생이 아니에요', '저는 학생이 없어요', '저는 학생 안이에요', '저는 학생이 아요'], explanation: 'Noun + 이/가 아니에요 = "is not (noun)". This is the negative of 이에요/예요.' },
  { category: 'Copula', question: 'How do you ask "Is there a book?"', answer: '책이 있어요?', options: ['책이 있어요?', '책이 이에요?', '책이 가요?', '책이 와요?'], explanation: 'Noun + 이/가 있어요 = there is / (I) have. 책 (consonant) → 책이 있어요?' },
  { category: 'Numbers', question: 'Which number system is used for counting objects (e.g., "three apples")?', answer: 'Native Korean (하나, 둘, 셋…)', options: ['Native Korean (하나, 둘, 셋…)', 'Sino-Korean (일, 이, 삼…)', 'Either system works', 'Arabic numerals only'], explanation: 'Native Korean numbers (하나/한, 둘/두, 셋/세…) are used with counters for objects and people.' },
  { category: 'Numbers', question: 'Which number system is used for prices and dates?', answer: 'Sino-Korean (일, 이, 삼…)', options: ['Sino-Korean (일, 이, 삼…)', 'Native Korean (하나, 둘, 셋…)', 'Either system works', 'Only Arabic numerals'], explanation: 'Sino-Korean (일, 이, 삼…) is used for money, dates, minutes, phone numbers.' },
]

// ── TOPIK II game questions ───────────────────────────────────────────────────

export const topikIIGrammarQuestions = [
  { category: 'Modals', question: 'How do you say "You must not smoke here"?', answer: '여기서 담배를 피우면 안 돼요', options: ['여기서 담배를 피우면 안 돼요', '여기서 담배를 피워야 해요', '여기서 담배를 피워도 돼요', '여기서 담배를 피우고 싶어요'], explanation: '-면 안 돼요 = prohibition ("must not"). -아야 해요 = "must do". -아도 돼요 = "may do".' },
  { category: 'Modals', question: 'How do you ask "May I take a photo here?"', answer: '여기서 사진을 찍어도 돼요?', options: ['여기서 사진을 찍어도 돼요?', '여기서 사진을 찍어야 해요?', '여기서 사진을 찍으면 안 돼요?', '여기서 사진을 찍을 거예요?'], explanation: '-아/어도 돼요? asks for permission ("May I...?").' },
  { category: 'Modals', question: 'How do you say "I have to study today"?', answer: '오늘 공부해야 해요', options: ['오늘 공부해야 해요', '오늘 공부해도 돼요', '오늘 공부하면 안 돼요', '오늘 공부할게요'], explanation: '-아야/어야 해요 expresses obligation ("must/have to"). 공부하다 → 공부해야 해요.' },
  { category: 'Indirect', question: 'How do you report: "My friend said they are going to Korea"?', answer: '친구가 한국에 간다고 했어요', options: ['친구가 한국에 간다고 했어요', '친구가 한국에 가라고 했어요', '친구가 한국에 가자고 했어요', '친구가 한국에 가냐고 했어요'], explanation: '-(ㄴ/는)다고 했어요 reports a statement. -라고 = command. -자고 = suggestion.' },
  { category: 'Indirect', question: 'How do you report: "The teacher told me to study"?', answer: '선생님이 공부하라고 했어요', options: ['선생님이 공부하라고 했어요', '선생님이 공부한다고 했어요', '선생님이 공부하자고 했어요', '선생님이 공부하냐고 했어요'], explanation: '-(으)라고 했어요 reports a command ("told to..."). -ㄴ/는다고 = statement. -자고 = suggestion.' },
  { category: 'Indirect', question: 'How do you report: "My friend suggested eating together"?', answer: '친구가 같이 밥 먹자고 했어요', options: ['친구가 같이 밥 먹자고 했어요', '친구가 같이 밥 먹는다고 했어요', '친구가 같이 밥 먹으라고 했어요', '친구가 같이 밥 먹냐고 했어요'], explanation: '-자고 했어요 reports a suggestion ("suggested to..."). The base is -자 (let\'s).' },
  { category: 'Passive', question: 'What is the passive form of 먹다 (to eat)?', answer: '먹히다', options: ['먹히다', '먹이다', '먹지다', '먹기다'], explanation: '먹다 → 먹히다 (to be eaten). The -히- suffix makes it passive.' },
  { category: 'Passive', question: 'How do you say "The weather got warmer"?', answer: '날씨가 따뜻해졌어요', options: ['날씨가 따뜻해졌어요', '날씨가 따뜻하게 했어요', '날씨가 따뜻해요', '날씨가 따뜻히어요'], explanation: '-아/어지다 expresses a change of state. 따뜻하다 → 따뜻해지다 (become warm).' },
  { category: 'Passive', question: 'What does 보이다 mean?', answer: 'To be seen / to be visible', options: ['To be seen / to be visible', 'To see', 'To look at', 'To show'], explanation: '보이다 is the passive of 보다 (see). Passive suffix -이- → 보이다 (to be seen).' },
  { category: 'AdvConnectives', question: '"음악을 들___ 공부해요." (study while listening to music)', answer: '으면서', options: ['으면서', '아도', '을수록', '는데'], explanation: '-면서 connects simultaneous actions (same subject). 듣다 → 들으면서.' },
  { category: 'AdvConnectives', question: '"바쁘___ 운동해요." (exercise even if busy)', answer: '아도', options: ['아도', '면서', '을수록', '는데'], explanation: '-아/어도 means "even if/though". 바쁘다 → 바빠도 (even if busy).' },
  { category: 'AdvConnectives', question: '"공부하___ 한국어가 재미있어요." (the more you study, the more interesting)', answer: 'ㄹ수록', options: ['ㄹ수록', '면서', '아도', '는데'], explanation: '-(으)ㄹ수록 = "the more...". 공부하다 → 공부할수록.' },
  { category: 'Modifiers', question: 'How do you say "the food I ate" (past modifier)?', answer: '먹은 음식', options: ['먹은 음식', '먹는 음식', '먹을 음식', '먹던 음식'], explanation: '-(으)ㄴ is the past modifier for action verbs. 먹다 → 먹은 (ate). -는 = present, -(으)ㄹ = future.' },
  { category: 'Modifiers', question: 'How do you say "the student studying Korean" (present modifier)?', answer: '한국어를 공부하는 학생', options: ['한국어를 공부하는 학생', '한국어를 공부한 학생', '한국어를 공부할 학생', '한국어를 공부하던 학생'], explanation: 'Action verbs use -는 for the present modifier. 공부하다 → 공부하는 (studying).' },
  { category: 'Modifiers', question: 'How do you say "Have you ever been to Korea?"', answer: '한국에 가 본 적이 있어요?', options: ['한국에 가 본 적이 있어요?', '한국에 갈 수 있어요?', '한국에 가고 싶어요?', '한국에 갈 것 같아요?'], explanation: '-(으)ㄴ 적이 있어요? asks about past experience. 가다 → 가 본 적이 있어요?' },
  { category: 'Inference', question: "How do you say \"It seems like it's raining\"?", answer: '비가 오는 것 같아요', options: ['비가 오는 것 같아요', '비가 올 것 같아요', '비가 온 것 같아요', '비가 오겠어요'], explanation: 'Present -는 것 같아요 = seems like (happening now). Future -(으)ㄹ 것 같아요 = seems like will happen.' },
  { category: 'Inference', question: 'Which ending expresses something the speaker personally discovered?', answer: '-더라고요', options: ['-더라고요', '-(으)ㄹ 것 같아요', '-는 것 같아요', '-겠어요'], explanation: '-더라고요 reports something personally witnessed/discovered. Cannot be used for yourself.' },
  { category: 'Inference', question: 'What does -겠- typically express?', answer: 'Volition, conjecture, or hedged speech', options: ['Volition, conjecture, or hedged speech', 'Past completed action', 'Ongoing action', 'Prohibition'], explanation: '-겠- expresses will, polite conjecture, or softened statements. E.g., 알겠어요 (I understand), 맛있겠다 (that looks delicious).' },
  { category: 'Formal', question: 'What is the formal polite form of "공부해요" (study)?', answer: '공부합니다', options: ['공부합니다', '공부하십시오', '공부하겠습니다', '공부하세요'], explanation: 'The formal polite declarative is -(스)ㅂ니다. 공부하다 → 공부합니다.' },
  { category: 'Formal', question: 'What is the formal command form of "앉다" (sit)?', answer: '앉으십시오', options: ['앉으십시오', '앉습니다', '앉으세요', '앉겠습니다'], explanation: '-십시오 is the formal command. 앉다 (consonant ending) → 앉으십시오.' },
  { category: 'Formal', question: 'The formal question form of "가다" (go) is:', answer: '갑니까?', options: ['갑니까?', '가십니까?', '갑니다', '가겠습니까?'], explanation: 'Formal question: -(스)ㅂ니까? 가다 (vowel/ㄹ) → 갑니까? (without -(으)시-).' },
  { category: 'Honorifics', question: 'How do you say "The teacher is coming" (with honorific)?', answer: '선생님이 오세요', options: ['선생님이 오세요', '선생님이 와요', '선생님이 옵니다', '선생님이 올 거예요'], explanation: '-(으)시- marks subject honorific. 오다 → 오시다 → 오세요 (polite with honorific).' },
  { category: 'Honorifics', question: 'What is the honorific form of 먹다 (to eat) for respected people?', answer: '드시다', options: ['드시다', '먹으시다', '잡수시다', '식사하다'], explanation: '드시다 is the special honorific replacement for 먹다. Both 드시다 and 잡수시다 are correct.' },
  { category: 'Honorifics', question: 'What word replaces 주다 (give) when giving to someone superior?', answer: '드리다', options: ['드리다', '받다', '드시다', '주시다'], explanation: '드리다 replaces 주다 when YOU give to a superior. 주시다 = they give to you (with honorific).' },
  { category: 'Honorifics', question: 'The honorific word for 이름 (name) is:', answer: '성함', options: ['성함', '댁', '연세', '말씀'], explanation: '이름 → 성함 (name). 집 → 댁 (home). 나이 → 연세 (age). 말 → 말씀 (speech).' },
]
