// TOPIK I Words - Beginner (Add all 1,671 from your PDF)
export const topikIWords = [
  { korean: '가게', english: 'store, shop', romanization: 'ga-ge', sentences: ['편의점 가게에 갔어요.', 'I went to the convenience store.'] },
  { korean: '가격', english: 'price', romanization: 'ga-gyeok', sentences: ['이 가격은 너무 비싸요.', 'This price is too expensive.'] },
  { korean: '가구', english: 'furniture', romanization: 'ga-gu', sentences: ['새 가구를 주문했어요.', 'I ordered new furniture.'] },
  { korean: '가깝다', english: 'close', romanization: 'ga-kkap-da', sentences: ['우리 집이 지하철역에 가까워요.', 'My house is close to the subway station.'] },
  { korean: '가끔', english: 'sometimes', romanization: 'ga-kkeum', sentences: ['가끔 친구를 만나요.', 'I sometimes meet friends.'] },
  { korean: '가다', english: 'go', romanization: 'ga-da', sentences: ['매일 회사에 가요.', 'I go to work every day.'] },
  { korean: '가르치다', english: 'teach', romanization: 'ga-reu-chi-da', sentences: ['대학교에서 영어를 가르쳐요.', 'I teach English at university.'] },
  { korean: '가방', english: 'bag', romanization: 'ga-bang', sentences: ['검은색 가방을 샀어요.', 'I bought a black bag.'] },
  { korean: '가볍다', english: 'light', romanization: 'ga-byeop-da', sentences: ['이 상자는 가벼워요.', 'This box is light.'] },
  { korean: '가수', english: 'singer', romanization: 'ga-su', sentences: ['제 친구는 가수가 되고 싶어요.', 'My friend wants to become a singer.'] },
  { korean: '가슴', english: 'chest', romanization: 'ga-seum', sentences: ['운동하면 가슴이 아파요.', 'My chest hurts when I exercise.'] },
  { korean: '가요', english: 'song', romanization: 'ga-yo', sentences: ['K-pop 가요를 좋아해요.', 'I like K-pop songs.'] },
  { korean: '가운데', english: 'middle', romanization: 'ga-un-de', sentences: ['테이블 가운데에 놓으세요.', 'Put it in the middle of the table.'] },
  { korean: '가위', english: 'scissors', romanization: 'ga-wi', sentences: ['가위가 어디 있어요?', 'Where are the scissors?'] },
  { korean: '가을', english: 'autumn', romanization: 'ga-eul', sentences: ['가을에 단풍을 봐요.', 'I see autumn leaves in fall.'] },
  { korean: '가장', english: 'most', romanization: 'ga-jang', sentences: ['이게 가장 좋아요.', 'This is the best.'] },
  { korean: '가져가다', english: 'take away', romanization: 'ga-jyeo-ga-da', sentences: ['필요하면 가져가세요.', 'Take it if you need it.'] },
  { korean: '가져오다', english: 'bring', romanization: 'ga-jyeo-o-da', sentences: ['내일 책을 가져올게요.', 'I will bring the book tomorrow.'] },
  { korean: '가족', english: 'family', romanization: 'ga-jok', sentences: ['주말에 가족을 만나요.', 'I meet my family on weekends.'] },
  { korean: '가지', english: 'branch', romanization: 'ga-ji', sentences: ['세 가지 방법이 있어요.', 'There are three methods.'] },
  { korean: '가지다', english: 'have', romanization: 'ga-ji-da', sentences: ['좋은 생각을 가지고 있어요.', 'I have a good idea.'] },
  { korean: '각', english: 'each', romanization: 'gak', sentences: ['각 학생이 발표해요.', 'Each student presents.'] },
  { korean: '간', english: 'while', romanization: 'gan', sentences: ['수업 간 쉬었어요.', 'I rested during class.'] },
  { korean: '간단하다', english: 'simple', romanization: 'gan-dan-ha-da', sentences: ['이 요리는 간단해요.', 'This dish is simple.'] },
  { korean: '간단히', english: 'simply', romanization: 'gan-dan-hi', sentences: ['간단히 점심을 먹었어요.', 'I ate lunch simply.'] },
  { korean: '간식', english: 'snack', romanization: 'gan-sik', sentences: ['오후에 간식을 먹어요.', 'I eat a snack in the afternoon.'] },
  { korean: '간장', english: 'soy sauce', romanization: 'gan-jang', sentences: ['간장을 좀 주세요.', 'Please pass the soy sauce.'] },
  { korean: '간호사', english: 'nurse', romanization: 'gan-ho-sa', sentences: ['병원에서 간호사로 일해요.', 'I work as a nurse at the hospital.'] },
  { korean: '갈비', english: 'ribs', romanization: 'gal-bi', sentences: ['갈비가 정말 맛있어요.', 'The ribs are really delicious.'] },
  { korean: '갈비탕', english: 'rib soup', romanization: 'gal-bi-tang', sentences: ['점심으로 갈비탕을 먹었어요.', 'I ate rib soup for lunch.'] },
  { korean: '갈색', english: 'brown', romanization: 'gal-saek', sentences: ['갈색 구두를 신었어요.', 'I wore brown shoes.'] },
  { korean: '갈아타다', english: 'transfer', romanization: 'ga-ra-ta-da', sentences: ['2호선에서 갈아타야 해요.', 'I have to transfer at Line 2.'] },
  { korean: '감', english: 'persimmon', romanization: 'gam', sentences: ['가을에 감을 많이 먹어요.', 'I eat a lot of persimmons in autumn.'] },
  { korean: '감기', english: 'cold', romanization: 'gam-gi', sentences: ['감기에 걸렸어요.', 'I caught a cold.'] },
  { korean: '감기약', english: 'cold medicine', romanization: 'gam-gi-yak', sentences: ['약국에서 감기약을 샀어요.', 'I bought cold medicine at the pharmacy.'] },
  { korean: '감다', english: 'close eyes', romanization: 'gam-da', sentences: ['눈을 감고 쉬세요.', 'Close your eyes and rest.'] },
  { korean: '감동', english: 'emotion', romanization: 'gam-dong', sentences: ['큰 감동을 받았어요.', 'I was deeply moved.'] },
  { korean: '감동하다', english: 'be impressed', romanization: 'gam-dong-ha-da', sentences: ['이 영화에 감동했어요.', 'I was impressed by this movie.'] },
  { korean: '감사', english: 'thanks', romanization: 'gam-sa', sentences: ['감사의 마음을 전해요.', 'I express my gratitude.'] },
  { korean: '감사드립니다', english: 'thank you (formal)', romanization: 'gam-sa-deu-rim-ni-da', sentences: ['초대해 주셔서 감사드립니다.', 'Thank you for inviting me.'] },
  { korean: '감사하다', english: 'thank', romanization: 'gam-sa-ha-da', sentences: ['항상 감사해요.', 'I\'m always grateful.'] },
  { korean: '감사합니다', english: 'thank you', romanization: 'gam-sa-ham-ni-da', sentences: ['도와주셔서 감사합니다.', 'Thank you for your help.'] },
  { korean: '감자', english: 'potato', romanization: 'gam-ja', sentences: ['감자 요리를 좋아해요.', 'I like potato dishes.'] },
  { korean: '감자탕', english: 'potato soup', romanization: 'gam-ja-tang', sentences: ['감자탕 한 그릇 주세요.', 'One bowl of potato soup, please.'] },
  { korean: '갑자기', english: 'suddenly', romanization: 'gap-ja-gi', sentences: ['갑자기 전화가 왔어요.', 'Suddenly, the phone rang.'] },
  { korean: '값', english: 'price', romanization: 'gap', sentences: ['값을 깎아 주세요.', 'Please give me a discount.'] },
  { korean: '강', english: 'river', romanization: 'gang', sentences: ['강에서 수영했어요.', 'I swam in the river.'] },
  { korean: '강아지', english: 'puppy', romanization: 'gang-a-ji', sentences: ['강아지를 키우고 싶어요.', 'I want to raise a puppy.'] },
  { korean: '강좌', english: 'lecture', romanization: 'gang-jwa', sentences: ['요리 강좌를 듣고 있어요.', 'I\'m taking a cooking class.'] },
  { korean: '갖다', english: 'have', romanization: 'gat-da', sentences: ['연필을 갖고 있어요?', 'Do you have a pencil?'] },
  { korean: '같다', english: 'same', romanization: 'gat-da', sentences: ['우리는 같은 반이에요.', 'We\'re in the same class.'] },
  { korean: '같이', english: 'together', romanization: 'ga-chi', sentences: ['같이 저녁 먹을까요?', 'Shall we eat dinner together?'] },
  { korean: '개', english: 'dog', romanization: 'gae', sentences: ['개가 짖어요.', 'The dog is barking.'] },
  { korean: '개나리', english: 'forsythia', romanization: 'gae-na-ri', sentences: ['봄에 개나리가 피어요.', 'Forsythias bloom in spring.'] },
  { korean: '개인', english: 'individual', romanization: 'gae-in', sentences: ['개인 시간이 필요해요.', 'I need personal time.'] },
  { korean: '거기', english: 'there', romanization: 'geo-gi', sentences: ['거기서 만나요.', 'Let\'s meet there.'] },
  { korean: '거리', english: 'street', romanization: 'geo-ri', sentences: ['거리가 깨끗해요.', 'The street is clean.'] },
  { korean: '거실', english: 'living room', romanization: 'geo-sil', sentences: ['거실에서 쉬어요.', 'I rest in the living room.'] },
  { korean: '거울', english: 'mirror', romanization: 'geo-ul', sentences: ['거울을 보고 화장해요.', 'I look in the mirror and put on makeup.'] },
  { korean: '거의', english: 'almost', romanization: 'geo-ui', sentences: ['거의 다 끝났어요.', 'It\'s almost finished.'] },
  { korean: '거짓말', english: 'lie', romanization: 'geo-jit-mal', sentences: ['거짓말하지 마세요.', 'Don\'t lie.'] },
  { korean: '걱정', english: 'worry', romanization: 'geok-jeong', sentences: ['걱정하지 마세요.', 'Don\'t worry.'] },
  { korean: '걱정하다', english: 'worry', romanization: 'geok-jeong-ha-da', sentences: ['시험을 걱정해요.', 'I worry about the exam.'] },
  { korean: '건강', english: 'health', romanization: 'geon-gang', sentences: ['건강이 가장 중요해요.', 'Health is most important.'] },
  { korean: '건강하다', english: 'be healthy', romanization: 'geon-gang-ha-da', sentences: ['할머니가 건강하세요.', 'Grandmother is healthy.'] },
  { korean: '건너가다', english: 'cross', romanization: 'geon-neo-ga-da', sentences: ['길을 건너갔어요.', 'I crossed the street.'] },
  { korean: '건너다', english: 'cross over', romanization: 'geon-neo-da', sentences: ['다리를 건너요.', 'I cross the bridge.'] },
  { korean: '건너편', english: 'other side', romanization: 'geon-neo-pyeon', sentences: ['건너편에 은행이 있어요.', 'There\'s a bank on the other side.'] },
  { korean: '건물', english: 'building', romanization: 'geon-mul', sentences: ['높은 건물이에요.', 'It\'s a tall building.'] },
  { korean: '건배', english: 'cheers', romanization: 'geon-bae', sentences: ['건배합시다!', 'Cheers!'] },
  { korean: '걷다', english: 'walk', romanization: 'geot-da', sentences: ['공원에서 걸어요.', 'I walk in the park.'] },
  { korean: '걸다', english: 'hang, call', romanization: 'geol-da', sentences: ['전화를 걸었어요.', 'I made a phone call.'] },
  { korean: '걸리다', english: 'take time', romanization: 'geol-li-da', sentences: ['30분 걸려요.', 'It takes 30 minutes.'] },
  { korean: '걸어가다', english: 'walk (go)', romanization: 'geo-reo-ga-da', sentences: ['학교까지 걸어가요.', 'I walk to school.'] },
  { korean: '걸어오다', english: 'walk (come)', romanization: 'geo-reo-o-da', sentences: ['집에서 걸어왔어요.', 'I walked from home.'] },
  { korean: '검은색', english: 'black', romanization: 'geo-meun-saek', sentences: ['검은색 옷을 입었어요.', 'I wore black clothes.'] },
  { korean: '것', english: 'thing', romanization: 'geot', sentences: ['좋은 것 같아요.', 'I think it\'s good.'] },
  { korean: '게임', english: 'game', romanization: 'ge-im', sentences: ['컴퓨터 게임을 해요.', 'I play computer games.'] },
  { korean: '겨울', english: 'winter', romanization: 'gyeo-ul', sentences: ['겨울이 추워요.', 'Winter is cold.'] },
  { korean: '겨울방학', english: 'winter vacation', romanization: 'gyeo-ul-bang-hak', sentences: ['겨울방학이 시작됐어요.', 'Winter vacation started.'] },
  { korean: '결과', english: 'result', romanization: 'gyeol-gwa', sentences: ['시험 결과가 좋아요.', 'The test results are good.'] },
  { korean: '결정', english: 'decision', romanization: 'gyeol-jeong', sentences: ['중요한 결정이에요.', 'It\'s an important decision.'] },
  { korean: '결정하다', english: 'decide', romanization: 'gyeol-jeong-ha-da', sentences: ['빨리 결정하세요.', 'Please decide quickly.'] },
  { korean: '결혼', english: 'marriage', romanization: 'gyeol-hon', sentences: ['내년에 결혼해요.', 'I\'m getting married next year.'] },
  { korean: '결혼식', english: 'wedding', romanization: 'gyeol-hon-sik', sentences: ['친구 결혼식에 갔어요.', 'I went to my friend\'s wedding.'] },
  { korean: '결혼하다', english: 'get married', romanization: 'gyeol-hon-ha-da', sentences: ['3년 전에 결혼했어요.', 'I got married 3 years ago.'] },
  { korean: '경기', english: 'game, match', romanization: 'gyeong-gi', sentences: ['축구 경기를 봤어요.', 'I watched a soccer game.'] },
  { korean: '경기장', english: 'stadium', romanization: 'gyeong-gi-jang', sentences: ['경기장에 사람이 많아요.', 'There are many people at the stadium.'] },
  { korean: '경복궁', english: 'Gyeongbokgung', romanization: 'gyeong-bok-gung', sentences: ['경복궁을 구경했어요.', 'I toured Gyeongbokgung Palace.'] },
  { korean: '경주', english: 'Gyeongju', romanization: 'gyeong-ju', sentences: ['경주에 여행 갔어요.', 'I traveled to Gyeongju.'] },
  { korean: '경찰', english: 'police', romanization: 'gyeong-chal', sentences: ['경찰에게 도움을 요청했어요.', 'I asked the police for help.'] },
  { korean: '경찰관', english: 'police officer', romanization: 'gyeong-chal-gwan', sentences: ['경찰관이 길을 안내했어요.', 'The police officer showed me the way.'] },
  { korean: '경찰서', english: 'police station', romanization: 'gyeong-chal-seo', sentences: ['경찰서가 가까워요.', 'The police station is nearby.'] },
  { korean: '경치', english: 'scenery', romanization: 'gyeong-chi', sentences: ['산 경치가 아름다워요.', 'The mountain scenery is beautiful.'] },
  { korean: '경험', english: 'experience', romanization: 'gyeong-heom', sentences: ['좋은 경험이었어요.', 'It was a good experience.'] },
  { korean: '계단', english: 'stairs', romanization: 'gye-dan', sentences: ['계단으로 올라가요.', 'I go up the stairs.'] },
  { korean: '계란', english: 'egg', romanization: 'gye-ran', sentences: ['아침에 계란을 먹어요.', 'I eat eggs in the morning.'] },
  { korean: '계산하다', english: 'calculate', romanization: 'gye-san-ha-da', sentences: ['돈을 계산했어요.', 'I calculated the money.'] },
  { korean: '계속', english: 'continue', romanization: 'gye-sok', sentences: ['계속 공부하세요.', 'Please continue studying.'] },
  { korean: '계시다', english: 'be (honorific)', romanization: 'gye-si-da', sentences: ['할아버지가 집에 계세요.', 'Grandfather is at home.'] },
  { korean: '계절', english: 'season', romanization: 'gye-jeol', sentences: ['어떤 계절을 좋아해요?', 'Which season do you like?'] },
  { korean: '계획', english: 'plan', romanization: 'gye-hoek', sentences: ['주말 계획이 있어요?', 'Do you have weekend plans?'] },
  { korean: '고기', english: 'meat', romanization: 'go-gi', sentences: ['고기를 구워요.', 'I grill meat.'] },
  { korean: '고등학교', english: 'high school', romanization: 'go-deung-hak-gyo', sentences: ['고등학교를 졸업했어요.', 'I graduated from high school.'] },
  { korean: '고등학생', english: 'high school student', romanization: 'go-deung-hak-saeng', sentences: ['제 동생은 고등학생이에요.', 'My sibling is a high school student.'] },
  { korean: '고르다', english: 'choose', romanization: 'go-reu-da', sentences: ['메뉴를 골랐어요.', 'I chose the menu.'] },
  { korean: '고마웠습니다', english: 'thank you (past)', romanization: 'go-ma-wot-seum-ni-da', sentences: ['어제 도와주셔서 고마웠습니다.', 'Thank you for helping yesterday.'] },
  { korean: '고맙다', english: 'thankful', romanization: 'go-map-da', sentences: ['정말 고마워요.', 'I\'m really thankful.'] },
  { korean: '고맙습니다', english: 'thank you', romanization: 'go-map-seum-ni-da', sentences: ['친절하게 대해주셔서 고맙습니다.', 'Thank you for your kindness.'] },
  { korean: '고모', english: 'paternal aunt', romanization: 'go-mo', sentences: ['고모 집에 놀러 가요.', 'I visit my aunt\'s house.'] },
  { korean: '고모부', english: 'paternal uncle', romanization: 'go-mo-bu', sentences: ['고모부가 오셨어요.', 'My uncle came.'] },
  { korean: '고속버스', english: 'express bus', romanization: 'go-sok-beo-seu', sentences: ['고속버스로 부산에 가요.', 'I go to Busan by express bus.'] },
  { korean: '고양이', english: 'cat', romanization: 'go-yang-i', sentences: ['고양이가 귀여워요.', 'The cat is cute.'] },
  { korean: '고장', english: 'broken', romanization: 'go-jang', sentences: ['컴퓨터가 고장 났어요.', 'The computer is broken.'] },
  { korean: '고추', english: 'red pepper', romanization: 'go-chu', sentences: ['고추가 매워요.', 'The pepper is spicy.'] },
  { korean: '고추장', english: 'red pepper paste', romanization: 'go-chu-jang', sentences: ['고추장을 넣었어요.', 'I added red pepper paste.'] },
  { korean: '고치다', english: 'fix', romanization: 'go-chi-da', sentences: ['자전거를 고쳤어요.', 'I fixed the bicycle.'] },
  { korean: '고프다', english: 'hungry', romanization: 'go-peu-da', sentences: ['배가 고파요.', 'I\'m hungry.'] },
  { korean: '고향', english: 'hometown', romanization: 'go-hyang', sentences: ['명절에 고향에 가요.', 'I go to my hometown for holidays.'] },
  { korean: '곧', english: 'soon', romanization: 'got', sentences: ['곧 도착해요.', 'I\'ll arrive soon.'] },
  { korean: '골목', english: 'alley', romanization: 'gol-mok', sentences: ['좁은 골목이에요.', 'It\'s a narrow alley.'] },
  { korean: '골프', english: 'golf', romanization: 'gol-peu', sentences: ['주말에 골프 쳐요.', 'I play golf on weekends.'] },
  { korean: '곱다', english: 'beautiful', romanization: 'gop-da', sentences: ['손이 고와요.', 'Her hands are beautiful.'] },
  { korean: '곳', english: 'place', romanization: 'got', sentences: ['좋은 곳을 알아요.', 'I know a good place.'] },
  { korean: '공', english: 'ball', romanization: 'gong', sentences: ['공을 던져요.', 'I throw the ball.'] },
  { korean: '공간', english: 'space', romanization: 'gong-gan', sentences: ['공간이 넓어요.', 'The space is wide.'] },
  { korean: '공기', english: 'air', romanization: 'gong-gi', sentences: ['공기가 맑아요.', 'The air is clear.'] },
  { korean: '공무원', english: 'public official', romanization: 'gong-mu-won', sentences: ['공무원 시험을 봐요.', 'I take the civil service exam.'] },
  { korean: '공부', english: 'study', romanization: 'gong-bu', sentences: ['열심히 공부해요.', 'I study hard.'] },
  { korean: '공부하다', english: 'study', romanization: 'gong-bu-ha-da', sentences: ['도서관에서 공부했어요.', 'I studied at the library.'] },
  { korean: '공연', english: 'performance', romanization: 'gong-yeon', sentences: ['음악 공연을 봤어요.', 'I watched a music performance.'] },
  { korean: '공원', english: 'park', romanization: 'gong-won', sentences: ['공원에서 산책해요.', 'I take a walk in the park.'] },
  { korean: '공중전화', english: 'payphone', romanization: 'gong-jung-jeon-hwa', sentences: ['공중전화가 없어요.', 'There\'s no payphone.'] },
  { korean: '공짜', english: 'free', romanization: 'gong-jja', sentences: ['공짜로 받았어요.', 'I got it for free.'] },
  { korean: '공책', english: 'notebook', romanization: 'gong-chaek', sentences: ['공책에 썼어요.', 'I wrote in the notebook.'] },
  { korean: '공항', english: 'airport', romanization: 'gong-hang', sentences: ['공항에 도착했어요.', 'I arrived at the airport.'] },
  { korean: '공휴일', english: 'public holiday', romanization: 'gong-hyu-il', sentences: ['내일은 공휴일이에요.', 'Tomorrow is a public holiday.'] },
  { korean: '과', english: 'department', romanization: 'gwa', sentences: ['경제학과 학생이에요.', 'I\'m an economics student.'] },
  { korean: '과거', english: 'past', romanization: 'gwa-geo', sentences: ['과거를 잊으세요.', 'Forget the past.'] },
  { korean: '과일', english: 'fruit', romanization: 'gwa-il', sentences: ['과일을 많이 먹어요.', 'I eat a lot of fruit.'] },
  { korean: '과자', english: 'snack', romanization: 'gwa-ja', sentences: ['과자를 사고 싶어요.', 'I want to buy snacks.'] },
  { korean: '과학', english: 'science', romanization: 'gwa-hak', sentences: ['과학을 좋아해요.', 'I like science.'] },
  { korean: '관계', english: 'relationship', romanization: 'gwan-gye', sentences: ['좋은 관계예요.', 'It\'s a good relationship.'] },
  { korean: '관광하다', english: 'sightsee', romanization: 'gwan-gwang-ha-da', sentences: ['서울을 관광했어요.', 'I sightsaw in Seoul.'] },
  { korean: '관심', english: 'interest', romanization: 'gwan-sim', sentences: ['한국어에 관심이 있어요.', 'I\'m interested in Korean.'] },
  { korean: '광고', english: 'advertisement', romanization: 'gwang-go', sentences: ['TV 광고를 봤어요.', 'I saw a TV advertisement.'] },
  { korean: '괜찮다', english: 'be okay', romanization: 'gwaen-chan-ta', sentences: ['괜찮아요, 걱정 마세요.', 'It\'s okay, don\'t worry.'] },
  { korean: '괜찮습니다', english: 'it\'s fine', romanization: 'gwaen-chan-seum-ni-da', sentences: ['도와주셔서 괜찮습니다.', 'It\'s fine, thank you for offering help.'] },
  { korean: '교과서', english: 'textbook', romanization: 'gyo-gwa-seo', sentences: ['교과서를 읽어요.', 'I read the textbook.'] },
  { korean: '교수', english: 'professor', romanization: 'gyo-su', sentences: ['교수님께 질문했어요.', 'I asked the professor a question.'] },
  { korean: '교실', english: 'classroom', romanization: 'gyo-sil', sentences: ['교실이 조용해요.', 'The classroom is quiet.'] },
  { korean: '교체', english: 'replace', romanization: 'gyo-che', sentences: ['배터리를 교체했어요.', 'I replaced the battery.'] },
  { korean: '교통', english: 'traffic', romanization: 'gyo-tong', sentences: ['교통이 복잡해요.', 'The traffic is heavy.'] },
  { korean: '교통사고', english: 'traffic accident', romanization: 'gyo-tong-sa-go', sentences: ['교통사고가 났어요.', 'There was a traffic accident.'] },
  { korean: '교회', english: 'church', romanization: 'gyo-hoe', sentences: ['일요일에 교회에 가요.', 'I go to church on Sunday.'] },
  { korean: '구', english: '9', romanization: 'gu', sentences: ['구호선을 타요.', 'I take Line 9.'] },
  { korean: '구경하다', english: 'look around', romanization: 'gu-gyeong-ha-da', sentences: ['시장을 구경했어요.', 'I looked around the market.'] },
  { korean: '구두', english: 'shoes', romanization: 'gu-du', sentences: ['새 구두를 샀어요.', 'I bought new shoes.'] },
  { korean: '구름', english: 'cloud', romanization: 'gu-reum', sentences: ['구름이 많아요.', 'There are many clouds.'] },
  { korean: '구십', english: '90', romanization: 'gu-sip', sentences: ['구십 점을 받았어요.', 'I got 90 points.'] },
  { korean: '구월', english: 'September', romanization: 'gu-wol', sentences: ['구월에 학교가 시작해요.', 'School starts in September.'] },
  { korean: '구하다', english: 'save, get', romanization: 'gu-ha-da', sentences: ['일자리를 구해요.', 'I\'m looking for a job.'] },
  { korean: '국', english: 'soup', romanization: 'guk', sentences: ['국이 뜨거워요.', 'The soup is hot.'] },
  { korean: '국내', english: 'domestic', romanization: 'guk-nae', sentences: ['국내 여행을 가요.', 'I go on a domestic trip.'] },
  { korean: '국립', english: 'national', romanization: 'guk-rip', sentences: ['국립 박물관이에요.', 'It\'s a national museum.'] },
  { korean: '국수', english: 'noodles', romanization: 'guk-su', sentences: ['국수를 먹었어요.', 'I ate noodles.'] },
  { korean: '국어', english: 'Korean language', romanization: 'gu-geo', sentences: ['국어 수업이 있어요.', 'I have Korean class.'] },
  { korean: '국적', english: 'nationality', romanization: 'guk-jeok', sentences: ['국적이 어떻게 돼요?', 'What\'s your nationality?'] },
  { korean: '국제', english: 'international', romanization: 'guk-je', sentences: ['국제 회의예요.', 'It\'s an international conference.'] },
  { korean: '군인', english: 'soldier', romanization: 'gu-nin', sentences: ['군인이 되고 싶어요.', 'I want to become a soldier.'] },
  { korean: '굽다', english: 'bake', romanization: 'gup-da', sentences: ['고기를 구워요.', 'I grill meat.'] },
  { korean: '권', english: 'book (counter)', romanization: 'gwon', sentences: ['책 두 권을 샀어요.', 'I bought two books.'] },
  { korean: '귀', english: 'ear', romanization: 'gwi', sentences: ['귀가 아파요.', 'My ear hurts.'] },
  { korean: '귀엽다', english: 'cute', romanization: 'gwi-yeop-da', sentences: ['아기가 귀여워요.', 'The baby is cute.'] },
  { korean: '규칙', english: 'rule', romanization: 'gyu-chik', sentences: ['규칙을 지켜요.', 'I follow the rules.'] },
  { korean: '귤', english: 'mandarin orange', romanization: 'gyul', sentences: ['귤을 까먹었어요.', 'I peeled and ate a mandarin.'] },
  { korean: '그', english: 'he, that', romanization: 'geu', sentences: ['그 사람을 알아요.', 'I know that person.'] },
  { korean: '그거', english: 'that thing', romanization: 'geu-geo', sentences: ['그거 주세요.', 'Give me that.'] },
  { korean: '그것', english: 'that', romanization: 'geu-geot', sentences: ['그것이 맞아요.', 'That\'s correct.'] },
  { korean: '그곳', english: 'that place', romanization: 'geu-got', sentences: ['그곳에 갔어요.', 'I went to that place.'] },
  { korean: '그날', english: 'that day', romanization: 'geu-nal', sentences: ['그날 비가 왔어요.', 'It rained that day.'] },
  { korean: '그냥', english: 'just', romanization: 'geu-nyang', sentences: ['그냥 집에 있을게요.', 'I\'ll just stay home.'] },
  { korean: '그동안', english: 'meanwhile', romanization: 'geu-dong-an', sentences: ['그동안 잘 지냈어요?', 'Have you been well meanwhile?'] },
  { korean: '그들', english: 'they', romanization: 'geu-deul', sentences: ['그들은 친구예요.', 'They are friends.'] },
  { korean: '그때', english: 'at that time', romanization: 'geu-ttae', sentences: ['그때 만났어요.', 'We met at that time.'] },
  { korean: '그래', english: 'yes, yeah', romanization: 'geu-rae', sentences: ['그래, 알았어.', 'Yeah, I got it.'] },
  { korean: '그래서', english: 'so', romanization: 'geu-rae-seo', sentences: ['피곤해요. 그래서 쉴게요.', 'I\'m tired, so I\'ll rest.'] },
  { korean: '그램', english: 'gram', romanization: 'geu-raem', sentences: ['100그램 주세요.', 'Give me 100 grams please.'] },
  { korean: '그러나', english: 'but', romanization: 'geu-reo-na', sentences: ['비싸요. 그러나 좋아요.', 'It\'s expensive, but it\'s good.'] },
  { korean: '그러니까', english: 'so, because', romanization: 'geu-reo-ni-kka', sentences: ['그러니까 조심하세요.', 'So please be careful.'] },
  { korean: '그러면', english: 'then', romanization: 'geu-reo-myeon', sentences: ['그러면 내일 만나요.', 'Then let\'s meet tomorrow.'] },
  { korean: '그런', english: 'such', romanization: 'geu-reon', sentences: ['그런 일이 있었어요.', 'Such a thing happened.'] },
  { korean: '그런데', english: 'but, by the way', romanization: 'geu-reon-de', sentences: ['맛있어요. 그런데 비싸요.', 'It\'s delicious, but expensive.'] },
  { korean: '그럼', english: 'then', romanization: 'geu-reom', sentences: ['그럼 나중에 봐요.', 'Then see you later.'] },
  { korean: '그렇게', english: 'like that', romanization: 'geu-reo-ke', sentences: ['그렇게 하지 마세요.', 'Don\'t do it like that.'] },
  { korean: '그렇구나', english: 'I see', romanization: 'geu-reo-ku-na', sentences: ['아, 그렇구나!', 'Oh, I see!'] },
  { korean: '그렇다', english: 'yes, that\'s right', romanization: 'geu-reo-ta', sentences: ['네, 그래요.', 'Yes, that\'s right.'] },
  { korean: '그렇습니다', english: 'that\'s right', romanization: 'geu-reo-seum-ni-da', sentences: ['네, 그렇습니다.', 'Yes, that\'s correct.'] },
  { korean: '그렇지만', english: 'but', romanization: 'geu-reo-chi-man', sentences: ['좋아요. 그렇지만 비싸요.', 'It\'s good, but expensive.'] },
  { korean: '그릇', english: 'bowl', romanization: 'geu-reut', sentences: ['그릇을 씻어요.', 'I wash the dishes.'] },
  { korean: '그리고', english: 'and', romanization: 'geu-ri-go', sentences: ['사과 그리고 바나나를 샀어요.', 'I bought apples and bananas.'] },
  { korean: '그리다', english: 'draw', romanization: 'geu-ri-da', sentences: ['그림을 그려요.', 'I draw a picture.'] },
  { korean: '그림', english: 'picture', romanization: 'geu-rim', sentences: ['벽에 그림이 걸려 있어요.', 'There\'s a picture hanging on the wall.'] },
  { korean: '그만', english: 'stop', romanization: 'geu-man', sentences: ['그만 먹을게요.', 'I\'ll stop eating.'] },
  { korean: '그분', english: 'that person (honorific)', romanization: 'geu-bun', sentences: ['그분은 선생님이세요.', 'That person is a teacher.'] },
  { korean: '그저께', english: 'day before yesterday', romanization: 'geu-jeo-kke', sentences: ['그저께 만났어요.', 'I met them the day before yesterday.'] },
  { korean: '그중', english: 'among them', romanization: 'geu-jung', sentences: ['그중에 하나를 고르세요.', 'Choose one among them.'] },
  { korean: '그쪽', english: 'that side', romanization: 'geu-jjok', sentences: ['그쪽으로 가세요.', 'Go that way.'] },
  { korean: '그치다', english: 'stop', romanization: 'geu-chi-da', sentences: ['비가 그쳤어요.', 'The rain stopped.'] },
  { korean: '극장', english: 'theater', romanization: 'geuk-jang', sentences: ['극장에서 영화를 봐요.', 'I watch movies at the theater.'] },
  { korean: '근처', english: 'nearby', romanization: 'geun-cheo', sentences: ['학교 근처에 살아요.', 'I live near the school.'] },
  { korean: '글', english: 'writing', romanization: 'geul', sentences: ['글을 잘 써요.', 'I write well.'] },
  { korean: '글쎄요', english: 'well, I guess', romanization: 'geul-sse-yo', sentences: ['글쎄요, 잘 모르겠어요.', 'Well, I\'m not sure.'] },
  { korean: '금방', english: 'soon', romanization: 'geum-bang', sentences: ['금방 돌아올게요.', 'I\'ll be right back.'] },
  { korean: '금연', english: 'no smoking', romanization: 'geu-myeon', sentences: ['여기는 금연이에요.', 'This is a non-smoking area.'] },
  { korean: '금요일', english: 'Friday', romanization: 'geu-myo-il', sentences: ['금요일에 만나요.', 'Let\'s meet on Friday.'] },
  { korean: '금주', english: 'this week', romanization: 'geum-ju', sentences: ['금주 금요일이에요.', 'It\'s this Friday.'] },
  { korean: '급', english: 'class, level', romanization: 'geup', sentences: ['초급반 학생이에요.', 'I\'m a beginner level student.'] },
  { korean: '급하다', english: 'urgent', romanization: 'geu-pa-da', sentences: ['일이 급해요.', 'The work is urgent.'] },
  { korean: '기간', english: 'period', romanization: 'gi-gan', sentences: ['한 달 기간이에요.', 'It\'s a one-month period.'] },
  { korean: '기다리다', english: 'wait', romanization: 'gi-da-ri-da', sentences: ['친구를 기다려요.', 'I wait for my friend.'] },
  { korean: '기르다', english: 'raise', romanization: 'gi-reu-da', sentences: ['고양이를 기워요.', 'I raise a cat.'] },
  { korean: '기름', english: 'oil', romanization: 'gi-reum', sentences: ['기름을 넣으세요.', 'Add oil.'] },
  { korean: '기분', english: 'feeling', romanization: 'gi-bun', sentences: ['기분이 좋아요.', 'I feel good.'] },
  { korean: '기뻐하다', english: 'be glad', romanization: 'gi-ppeo-ha-da', sentences: ['선물을 받고 기뻐했어요.', 'I was glad to receive the gift.'] },
  { korean: '기쁘다', english: 'happy', romanization: 'gi-ppeu-da', sentences: ['만나서 기뻐요.', 'I\'m happy to meet you.'] },
  { korean: '기사', english: 'article, driver', romanization: 'gi-sa', sentences: ['신문 기사를 읽었어요.', 'I read a newspaper article.'] },
  { korean: '기숙사', english: 'dormitory', romanization: 'gi-suk-sa', sentences: ['기숙사에서 살아요.', 'I live in the dormitory.'] },
  { korean: '기억하다', english: 'remember', romanization: 'gi-eok-ha-da', sentences: ['이름을 기억해요.', 'I remember the name.'] },
  { korean: '기온', english: 'temperature', romanization: 'gi-on', sentences: ['오늘 기온이 높아요.', 'Today\'s temperature is high.'] },
  { korean: '기자', english: 'reporter', romanization: 'gi-ja', sentences: ['기자가 인터뷰했어요.', 'The reporter interviewed me.'] },
  { korean: '기차', english: 'train', romanization: 'gi-cha', sentences: ['기차로 여행해요.', 'I travel by train.'] },
  { korean: '기침', english: 'cough', romanization: 'gi-chim', sentences: ['기침이 심해요.', 'I have a bad cough.'] },
  { korean: '기타', english: 'guitar, etc', romanization: 'gi-ta', sentences: ['기타를 쳐요.', 'I play guitar.'] },
  { korean: '긴장되다', english: 'be nervous', romanization: 'gin-jang-doe-da', sentences: ['시험 전에 긴장돼요.', 'I get nervous before exams.'] },
  { korean: '길', english: 'road', romanization: 'gil', sentences: ['길이 막혀요.', 'The road is blocked.'] },
  { korean: '길다', english: 'long', romanization: 'gil-da', sentences: ['머리가 길어요.', 'My hair is long.'] },
  { korean: '김', english: 'seaweed', romanization: 'gim', sentences: ['김을 먹어요.', 'I eat seaweed.'] },
  { korean: '김밥', english: 'kimbap', romanization: 'gim-bap', sentences: ['점심으로 김밥을 먹었어요.', 'I ate kimbap for lunch.'] },
  { korean: '김치', english: 'kimchi', romanization: 'gim-chi', sentences: ['김치가 맛있어요.', 'Kimchi is delicious.'] },
  { korean: '김치찌개', english: 'kimchi stew', romanization: 'gim-chi-jji-gae', sentences: ['김치찌개를 끓였어요.', 'I made kimchi stew.'] },
  { korean: '김포공항', english: 'Gimpo Airport', romanization: 'gim-po-gong-hang', sentences: ['김포공항에서 만나요.', 'Let\'s meet at Gimpo Airport.'] },
  { korean: '까만색', english: 'black color', romanization: 'kka-man-saek', sentences: ['까만색 옷을 입어요.', 'I wear black clothes.'] },
  { korean: '까맣다', english: 'black', romanization: 'kka-ma-ta', sentences: ['머리가 까매요.', 'The hair is black.'] },
  { korean: '깎다', english: 'cut, shave', romanization: 'kkak-da', sentences: ['머리를 깎았어요.', 'I cut my hair.'] },
  { korean: '깜짝', english: 'surprised', romanization: 'kkam-jjak', sentences: ['깜짝 놀랐어요.', 'I was startled.'] },
  { korean: '깨끗하다', english: 'clean', romanization: 'kkae-kkeu-ta-da', sentences: ['방이 깨끗해요.', 'The room is clean.'] },
  { korean: '깨다', english: 'wake up', romanization: 'kkae-da', sentences: ['아침 일찍 깼어요.', 'I woke up early in the morning.'] },
  { korean: '깨지다', english: 'break', romanization: 'kkae-ji-da', sentences: ['유리가 깨졌어요.', 'The glass broke.'] },
  { korean: '꺼내다', english: 'take out', romanization: 'kkeo-nae-da', sentences: ['가방에서 책을 꺼냈어요.', 'I took the book out of the bag.'] },
  { korean: '껌', english: 'chewing gum', romanization: 'kkeom', sentences: ['껌을 씹어요.', 'I chew gum.'] },
  { korean: '꼭', english: 'exactly, must', romanization: 'kkok', sentences: ['꼭 와야 해요.', 'You must come.'] },
  { korean: '꽃', english: 'flower', romanization: 'kkot', sentences: ['예쁜 꽃이 피었어요.', 'Beautiful flowers bloomed.'] },
  { korean: '꽃집', english: 'flower shop', romanization: 'kkot-jip', sentences: ['꽃집에서 장미를 샀어요.', 'I bought roses at the flower shop.'] },
  { korean: '꾸다', english: 'dream', romanization: 'kku-da', sentences: ['꿈을 꿨어요.', 'I had a dream.'] },
  { korean: '꿈', english: 'dream', romanization: 'kkum', sentences: ['좋은 꿈 꾸세요.', 'Have sweet dreams.'] },
  { korean: '끄다', english: 'turn off', romanization: 'kkeu-da', sentences: ['불을 껐어요.', 'I turned off the light.'] },
  { korean: '끓이다', english: 'boil', romanization: 'kkeu-ri-da', sentences: ['물을 끓여요.', 'I boil water.'] },
  { korean: '끝', english: 'end', romanization: 'kkeut', sentences: ['영화가 끝났어요.', 'The movie ended.'] },
  { korean: '끝나다', english: 'finish', romanization: 'kkeun-na-da', sentences: ['수업이 끝났어요.', 'Class finished.'] },
  { korean: '끝내다', english: 'finish', romanization: 'kkeun-nae-da', sentences: ['숙제를 끝냈어요.', 'I finished my homework.'] },
  { korean: '끼다', english: 'wear, put on', romanization: 'kki-da', sentences: ['장갑을 껴요.', 'I wear gloves.'] },
  { korean: '나', english: 'I', romanization: 'na', sentences: ['나는 학생이에요.', 'I am a student.'] },
  { korean: '나가다', english: 'go out', romanization: 'na-ga-da', sentences: ['밖에 나갔어요.', 'I went outside.'] },
  { korean: '나누다', english: 'share, divide', romanization: 'na-nu-da', sentences: ['친구와 음식을 나눠 먹었어요.', 'I shared food with my friend.'] },
  { korean: '나다', english: 'occur', romanization: 'na-da', sentences: ['불이 났어요!', 'A fire broke out!'] },
  { korean: '나라', english: 'country', romanization: 'na-ra', sentences: ['어느 나라 사람이에요?', 'What country are you from?'] },
  { korean: '나무', english: 'tree', romanization: 'na-mu', sentences: ['나무가 많아요.', 'There are many trees.'] },
  { korean: '나빠지다', english: 'get worse', romanization: 'na-ppa-ji-da', sentences: ['날씨가 나빠졌어요.', 'The weather got worse.'] },
  { korean: '나쁘다', english: 'bad', romanization: 'na-ppeu-da', sentences: ['이 음식은 나빠요.', 'This food is bad.'] },
  { korean: '나오다', english: 'come out', romanization: 'na-o-da', sentences: ['밖으로 나왔어요.', 'I came outside.'] },
  { korean: '나이', english: 'age', romanization: 'na-i', sentences: ['나이가 어떻게 돼요?', 'How old are you?'] },
  { korean: '나중', english: 'later', romanization: 'na-jung', sentences: ['나중에 전화할게요.', 'I\'ll call you later.'] },
  { korean: '나타나다', english: 'appear', romanization: 'na-ta-na-da', sentences: ['갑자기 나타났어요.', 'It suddenly appeared.'] },
  { korean: '나흘', english: 'four days', romanization: 'na-heul', sentences: ['나흘 동안 여행했어요.', 'I traveled for four days.'] },
  { korean: '낚시', english: 'fishing', romanization: 'nak-si', sentences: ['강에서 낚시해요.', 'I fish in the river.'] },
  { korean: '날', english: 'day', romanization: 'nal', sentences: ['좋은 날이에요.', 'It\'s a good day.'] },
  { korean: '날씨', english: 'weather', romanization: 'nal-ssi', sentences: ['오늘 날씨가 좋아요.', 'The weather is nice today.'] },
  { korean: '날짜', english: 'date', romanization: 'nal-jja', sentences: ['날짜를 확인하세요.', 'Check the date.'] },
  { korean: '남', english: 'south, man', romanization: 'nam', sentences: ['남쪽으로 가요.', 'I go south.'] },
  { korean: '남기다', english: 'leave', romanization: 'nam-gi-da', sentences: ['음식을 남겼어요.', 'I left food.'] },
  { korean: '남녀', english: 'men and women', romanization: 'nam-nyeo', sentences: ['남녀 모두 환영해요.', 'Both men and women are welcome.'] },
  { korean: '남대문시장', english: 'Namdaemun Market', romanization: 'nam-dae-mun-si-jang', sentences: ['남대문시장에서 쇼핑했어요.', 'I shopped at Namdaemun Market.'] },
  { korean: '남동생', english: 'younger brother', romanization: 'nam-dong-saeng', sentences: ['남동생이 한 명 있어요.', 'I have one younger brother.'] },
  { korean: '남미', english: 'South America', romanization: 'nam-mi', sentences: ['남미 여행을 가고 싶어요.', 'I want to travel to South America.'] },
  { korean: '남북', english: 'north and south', romanization: 'nam-buk', sentences: ['남북 관계가 중요해요.', 'North-South relations are important.'] },
  { korean: '남자', english: 'man', romanization: 'nam-ja', sentences: ['키가 큰 남자예요.', 'He\'s a tall man.'] },
  { korean: '남쪽', english: 'south', romanization: 'nam-jjok', sentences: ['남쪽 지방은 따뜻해요.', 'The southern region is warm.'] },
  { korean: '남편', english: 'husband', romanization: 'nam-pyeon', sentences: ['제 남편을 소개할게요.', 'I\'ll introduce my husband.'] },
  { korean: '남학생', english: 'male student', romanization: 'nam-hak-saeng', sentences: ['우리 반에 남학생이 많아요.', 'There are many male students in our class.'] },
  { korean: '낮', english: 'daytime', romanization: 'nat', sentences: ['낮에는 일해요.', 'I work during the day.'] },
  { korean: '낮다', english: 'low', romanization: 'nat-da', sentences: ['목소리가 낮아요.', 'The voice is low.'] },
  { korean: '내', english: 'my', romanization: 'nae', sentences: ['내 가방이에요.', 'It\'s my bag.'] },
  { korean: '내가', english: 'I (subject)', romanization: 'nae-ga', sentences: ['내가 할게요.', 'I\'ll do it.'] },
  { korean: '내과', english: 'internal medicine', romanization: 'nae-gwa', sentences: ['내과에 갔어요.', 'I went to internal medicine.'] },
  { korean: '내년', english: 'next year', romanization: 'nae-nyeon', sentences: ['내년에 졸업해요.', 'I graduate next year.'] },
  { korean: '내다', english: 'pay, submit', romanization: 'nae-da', sentences: ['돈을 냈어요.', 'I paid the money.'] },
  { korean: '내려가다', english: 'go down', romanization: 'nae-ryeo-ga-da', sentences: ['계단을 내려갔어요.', 'I went down the stairs.'] },
  { korean: '내려오다', english: 'come down', romanization: 'nae-ryeo-o-da', sentences: ['산에서 내려왔어요.', 'I came down from the mountain.'] },
  { korean: '내리다', english: 'get off', romanization: 'nae-ri-da', sentences: ['다음 역에서 내려요.', 'I get off at the next station.'] },
  { korean: '내용', english: 'content', romanization: 'nae-yong', sentences: ['이야기 내용이 재미있어요.', 'The story content is interesting.'] },
  { korean: '내일', english: 'tomorrow', romanization: 'nae-il', sentences: ['내일 만나요.', 'See you tomorrow.'] },
  { korean: '냄비', english: 'pot', romanization: 'naem-bi', sentences: ['냄비에 물을 끓여요.', 'I boil water in the pot.'] },
  { korean: '냄새', english: 'smell', romanization: 'naem-sae', sentences: ['좋은 냄새가 나요.', 'It smells good.'] },
  { korean: '냉면', english: 'cold noodles', romanization: 'naeng-myeon', sentences: ['여름에 냉면을 먹어요.', 'I eat cold noodles in summer.'] },
  { korean: '냉장고', english: 'refrigerator', romanization: 'naeng-jang-go', sentences: ['냉장고에 넣으세요.', 'Put it in the refrigerator.'] },
  { korean: '너', english: 'you', romanization: 'neo', sentences: ['너는 학생이야?', 'Are you a student?'] },
  { korean: '너무', english: 'too, very', romanization: 'neo-mu', sentences: ['너무 비싸요.', 'It\'s too expensive.'] },
  { korean: '넓다', english: 'wide', romanization: 'neol-da', sentences: ['방이 넓어요.', 'The room is spacious.'] },
  { korean: '넘다', english: 'exceed', romanization: 'neom-da', sentences: ['시간을 넘었어요.', 'It exceeded the time.'] },
  { korean: '넘어지다', english: 'fall down', romanization: 'neo-meo-ji-da', sentences: ['길에서 넘어졌어요.', 'I fell on the street.'] },
  { korean: '넣다', english: 'put in', romanization: 'neo-ta', sentences: ['가방에 넣었어요.', 'I put it in the bag.'] },
  { korean: '네', english: 'yes, four', romanization: 'ne', sentences: ['네, 알겠습니다.', 'Yes, I understand.'] },
  { korean: '넥타이', english: 'necktie', romanization: 'nek-ta-i', sentences: ['넥타이를 매요.', 'I wear a tie.'] },
  { korean: '넷', english: 'four', romanization: 'net', sentences: ['우리는 넷이에요.', 'There are four of us.'] },
  { korean: '넷째', english: 'fourth', romanization: 'net-jjae', sentences: ['넷째 줄에 앉으세요.', 'Sit in the fourth row.'] },
  { korean: '년', english: 'year', romanization: 'nyeon', sentences: ['5년 전이에요.', 'It was 5 years ago.'] },
  { korean: '노란색', english: 'yellow', romanization: 'no-ran-saek', sentences: ['노란색 꽃이 예뻐요.', 'Yellow flowers are pretty.'] },
  { korean: '노랗다', english: 'yellow', romanization: 'no-ra-ta', sentences: ['바나나가 노래요.', 'The banana is yellow.'] },
  { korean: '노래', english: 'song', romanization: 'no-rae', sentences: ['노래를 불러요.', 'I sing a song.'] },
  { korean: '노래방', english: 'karaoke', romanization: 'no-rae-bang', sentences: ['노래방에 자주 가요.', 'I often go to karaoke.'] },
  { korean: '노래하다', english: 'sing', romanization: 'no-rae-ha-da', sentences: ['친구와 노래했어요.', 'I sang with friends.'] },
  { korean: '노력하다', english: 'make an effort', romanization: 'no-ryeo-ka-da', sentences: ['열심히 노력해요.', 'I try hard.'] },
  { korean: '노트', english: 'notebook', romanization: 'no-teu', sentences: ['노트에 적어요.', 'I write in the notebook.'] },
  { korean: '녹색', english: 'green', romanization: 'nok-saek', sentences: ['녹색 옷을 입었어요.', 'I wore green clothes.'] },
  { korean: '녹차', english: 'green tea', romanization: 'nok-cha', sentences: ['녹차를 마셔요.', 'I drink green tea.'] },
  { korean: '놀다', english: 'play', romanization: 'nol-da', sentences: ['친구와 놀았어요.', 'I played with friends.'] },
  { korean: '놀라다', english: 'be surprised', romanization: 'nol-la-da', sentences: ['소식을 듣고 놀랐어요.', 'I was surprised to hear the news.'] },
  { korean: '농구', english: 'basketball', romanization: 'nong-gu', sentences: ['농구를 잘 쳐요.', 'I play basketball well.'] },
  { korean: '높다', english: 'high', romanization: 'nop-da', sentences: ['산이 높아요.', 'The mountain is high.'] },
  { korean: '놓다', english: 'put, place', romanization: 'no-ta', sentences: ['책상 위에 놓으세요.', 'Put it on the desk.'] },
  { korean: '누가', english: 'who (subject)', romanization: 'nu-ga', sentences: ['누가 왔어요?', 'Who came?'] },
  { korean: '누구', english: 'who', romanization: 'nu-gu', sentences: ['누구세요?', 'Who are you?'] },
  { korean: '누나', english: 'older sister (from male)', romanization: 'nu-na', sentences: ['누나가 두 명 있어요.', 'I have two older sisters.'] },
  { korean: '누르다', english: 'press', romanization: 'nu-reu-da', sentences: ['버튼을 눌러요.', 'I press the button.'] },
  { korean: '눈', english: 'eye, snow', romanization: 'nun', sentences: ['눈이 와요.', 'It\'s snowing.'] },
  { korean: '눈물', english: 'tears', romanization: 'nun-mul', sentences: ['눈물이 났어요.', 'Tears came out.'] },
  { korean: '눈사람', english: 'snowman', romanization: 'nun-sa-ram', sentences: ['눈사람을 만들었어요.', 'I made a snowman.'] },
  { korean: '눕다', english: 'lie down', romanization: 'nup-da', sentences: ['침대에 누워요.', 'I lie down on the bed.'] },
  { korean: '뉴스', english: 'news', romanization: 'nyu-seu', sentences: ['뉴스를 봤어요.', 'I watched the news.'] },
  { korean: '뉴욕', english: 'New York', romanization: 'nyu-yok', sentences: ['뉴욕에 가고 싶어요.', 'I want to go to New York.'] },
  { korean: '느끼다', english: 'feel', romanization: 'neu-kki-da', sentences: ['행복을 느껴요.', 'I feel happy.'] },
  { korean: '느낌', english: 'feeling', romanization: 'neu-kkim', sentences: ['좋은 느낌이에요.', 'It\'s a good feeling.'] },
  { korean: '느리다', english: 'slow', romanization: 'neu-ri-da', sentences: ['버스가 느려요.', 'The bus is slow.'] },
  { korean: '늘', english: 'always', romanization: 'neul', sentences: ['늘 감사해요.', 'I\'m always grateful.'] },
  { korean: '늘다', english: 'increase', romanization: 'neul-da', sentences: ['실력이 늘었어요.', 'My skills increased.'] },
  { korean: '능력', english: 'ability', romanization: 'neung-ryeok', sentences: ['능력이 뛰어나요.', 'The ability is outstanding.'] },
  { korean: '늦다', english: 'late', romanization: 'neut-da', sentences: ['학교에 늦었어요.', 'I was late for school.'] },
  { korean: '늦잠', english: 'oversleep', romanization: 'neut-jam', sentences: ['늦잠을 잤어요.', 'I overslept.'] },
  { korean: '님', english: 'honorific suffix', romanization: 'nim', sentences: ['선생님께 인사했어요.', 'I greeted the teacher.'] },
  { korean: '다', english: 'all', romanization: 'da', sentences: ['다 먹었어요.', 'I ate it all.'] },
  { korean: '다녀오다', english: 'go and come back', romanization: 'da-nyeo-o-da', sentences: ['학교 다녀왔어요.', 'I\'m back from school.'] },
  { korean: '다니다', english: 'attend', romanization: 'da-ni-da', sentences: ['대학교에 다녀요.', 'I attend university.'] },
  { korean: '다르다', english: 'different', romanization: 'da-reu-da', sentences: ['생각이 달라요.', 'Our thoughts are different.'] },
  { korean: '다른', english: 'other', romanization: 'da-reun', sentences: ['다른 것을 주세요.', 'Give me another one.'] },
  { korean: '다리', english: 'leg, bridge', romanization: 'da-ri', sentences: ['다리가 아파요.', 'My leg hurts.'] },
  { korean: '다섯', english: 'five', romanization: 'da-seot', sentences: ['다섯 시에 만나요.', 'Let\'s meet at five o\'clock.'] },
  { korean: '다시', english: 'again', romanization: 'da-si', sentences: ['다시 해 보세요.', 'Try again.'] },
  { korean: '다음', english: 'next', romanization: 'da-eum', sentences: ['다음 주에 시험이에요.', 'The exam is next week.'] },
  { korean: '다음달', english: 'next month', romanization: 'da-eum-dal', sentences: ['다음달에 이사해요.', 'I\'m moving next month.'] },
  { korean: '다음주', english: 'next week', romanization: 'da-eum-ju', sentences: ['다음주에 만나요.', 'Let\'s meet next week.'] },
  { korean: '다음해', english: 'next year', romanization: 'da-eum-hae', sentences: ['다음해 계획이에요.', 'It\'s a plan for next year.'] },
  { korean: '다이어트', english: 'diet', romanization: 'da-i-eo-teu', sentences: ['다이어트 중이에요.', 'I\'m on a diet.'] },
  { korean: '다치다', english: 'get hurt', romanization: 'da-chi-da', sentences: ['손을 다쳤어요.', 'I hurt my hand.'] },
  { korean: '닦다', english: 'wipe', romanization: 'dak-da', sentences: ['창문을 닦았어요.', 'I wiped the window.'] },
  { korean: '단어', english: 'word', romanization: 'da-neo', sentences: ['새로운 단어를 배워요.', 'I learn new words.'] },
  { korean: '단점', english: 'disadvantage', romanization: 'dan-jeom', sentences: ['단점이 있어요.', 'There are disadvantages.'] },
  { korean: '닫다', english: 'close', romanization: 'dat-da', sentences: ['문을 닫으세요.', 'Please close the door.'] },
  { korean: '닫히다', english: 'be closed', romanization: 'da-chi-da', sentences: ['문이 닫혔어요.', 'The door closed.'] },
  { korean: '달', english: 'month, moon', romanization: 'dal', sentences: ['달이 밝아요.', 'The moon is bright.'] },
  { korean: '달걀', english: 'egg', romanization: 'dal-gyal', sentences: ['달걀을 삶았어요.', 'I boiled eggs.'] },
  { korean: '달다', english: 'sweet', romanization: 'dal-da', sentences: ['케이크가 달아요.', 'The cake is sweet.'] },
  { korean: '달러', english: 'dollar', romanization: 'dal-leo', sentences: ['100달러예요.', 'It\'s 100 dollars.'] },
  { korean: '달력', english: 'calendar', romanization: 'dal-lyeok', sentences: ['달력을 봤어요.', 'I looked at the calendar.'] },
  { korean: '달리다', english: 'run', romanization: 'dal-li-da', sentences: ['빨리 달려요.', 'I run fast.'] },
  { korean: '닭', english: 'chicken', romanization: 'dak', sentences: ['닭을 키워요.', 'I raise chickens.'] },
  { korean: '닭고기', english: 'chicken meat', romanization: 'dak-go-gi', sentences: ['닭고기를 구웠어요.', 'I grilled chicken.'] },
  { korean: '닮다', english: 'resemble', romanization: 'dam-da', sentences: ['엄마를 닮았어요.', 'I resemble my mom.'] },
  { korean: '담그다', english: 'pickle', romanization: 'dam-geu-da', sentences: ['김치를 담갔어요.', 'I made kimchi.'] },
  { korean: '담배', english: 'cigarette', romanization: 'dam-bae', sentences: ['담배를 피우지 마세요.', 'Don\'t smoke.'] },
  { korean: '답장', english: 'reply', romanization: 'dap-jang', sentences: ['답장을 보냈어요.', 'I sent a reply.'] },
  { korean: '당근', english: 'carrot', romanization: 'dang-geun', sentences: ['당근을 잘라요.', 'I cut carrots.'] },
  { korean: '당신', english: 'you', romanization: 'dang-sin', sentences: ['당신을 사랑해요.', 'I love you.'] },
  { korean: '대', english: 'versus', romanization: 'dae', sentences: ['3대 2로 이겼어요.', 'We won 3 to 2.'] },
  { korean: '대답', english: 'answer', romanization: 'dae-dap', sentences: ['대답을 들었어요.', 'I heard the answer.'] },
  { korean: '대답하다', english: 'answer', romanization: 'dae-da-pa-da', sentences: ['질문에 대답했어요.', 'I answered the question.'] },
  { korean: '대부분', english: 'most', romanization: 'dae-bu-bun', sentences: ['대부분 학생들이 왔어요.', 'Most students came.'] },
  { korean: '대사관', english: 'embassy', romanization: 'dae-sa-gwan', sentences: ['대사관에 갔어요.', 'I went to the embassy.'] },
  { korean: '대학', english: 'university', romanization: 'dae-hak', sentences: ['대학에 입학했어요.', 'I entered university.'] },
  { korean: '대학교', english: 'university', romanization: 'dae-hak-gyo', sentences: ['대학교를 졸업했어요.', 'I graduated from university.'] },
  { korean: '대학생', english: 'college student', romanization: 'dae-hak-saeng', sentences: ['저는 대학생이에요.', 'I\'m a college student.'] },
  { korean: '대학원', english: 'graduate school', romanization: 'dae-ha-gwon', sentences: ['대학원에 진학해요.', 'I\'m going to graduate school.'] },
  { korean: '대학원생', english: 'graduate student', romanization: 'dae-ha-gwon-saeng', sentences: ['대학원생이에요.', 'I\'m a graduate student.'] },
  { korean: '대한민국', english: 'South Korea', romanization: 'dae-han-min-guk', sentences: ['대한민국 국민이에요.', 'I\'m a citizen of South Korea.'] },
  { korean: '대화', english: 'conversation', romanization: 'dae-hwa', sentences: ['대화를 나눴어요.', 'We had a conversation.'] },
  { korean: '대회', english: 'competition', romanization: 'dae-hoe', sentences: ['대회에 참가해요.', 'I participate in the competition.'] },
  { korean: '댁', english: 'house (honorific)', romanization: 'daek', sentences: ['댁이 어디세요?', 'Where do you live?'] },
  { korean: '더', english: 'more', romanization: 'deo', sentences: ['더 먹을래요?', 'Do you want to eat more?'] },
  { korean: '더럽다', english: 'dirty', romanization: 'deo-reop-da', sentences: ['옷이 더러워요.', 'The clothes are dirty.'] },
  { korean: '더운물', english: 'hot water', romanization: 'deo-un-mul', sentences: ['더운물로 씻어요.', 'I wash with hot water.'] },
  { korean: '덕분', english: 'thanks to', romanization: 'deok-bun', sentences: ['덕분에 성공했어요.', 'Thanks to you, I succeeded.'] },
  { korean: '덥다', english: 'hot', romanization: 'deop-da', sentences: ['여름이 더워요.', 'Summer is hot.'] },
  { korean: '덮다', english: 'cover', romanization: 'deop-da', sentences: ['이불로 덮었어요.', 'I covered with a blanket.'] },
  { korean: '데리다', english: 'bring along', romanization: 'de-ri-da', sentences: ['동생을 데려왔어요.', 'I brought my younger sibling.'] },
  { korean: '데이트', english: 'date', romanization: 'de-i-teu', sentences: ['데이트했어요.', 'I went on a date.'] },
  { korean: '도로', english: 'road', romanization: 'do-ro', sentences: ['도로가 넓어요.', 'The road is wide.'] },
  { korean: '도서관', english: 'library', romanization: 'do-seo-gwan', sentences: ['도서관에서 공부해요.', 'I study at the library.'] },
  { korean: '도시', english: 'city', romanization: 'do-si', sentences: ['큰 도시예요.', 'It\'s a big city.'] },
  { korean: '도와주다', english: 'help', romanization: 'do-wa-ju-da', sentences: ['도와주셔서 고마워요.', 'Thank you for helping.'] },
  { korean: '도움', english: 'help', romanization: 'do-um', sentences: ['도움이 필요해요.', 'I need help.'] },
  { korean: '도착', english: 'arrival', romanization: 'do-chak', sentences: ['도착 시간이 언제예요?', 'When is the arrival time?'] },
  { korean: '도착하다', english: 'arrive', romanization: 'do-cha-ka-da', sentences: ['공항에 도착했어요.', 'I arrived at the airport.'] },
  { korean: '도쿄', english: 'Tokyo', romanization: 'do-kyo', sentences: ['도쿄에 여행 갔어요.', 'I traveled to Tokyo.'] },
  { korean: '독서', english: 'reading', romanization: 'dok-seo', sentences: ['독서를 좋아해요.', 'I like reading.'] },
  { korean: '독서실', english: 'reading room', romanization: 'dok-seo-sil', sentences: ['독서실에서 공부해요.', 'I study in the reading room.'] },
  { korean: '독서하다', english: 'read', romanization: 'dok-seo-ha-da', sentences: ['주말에 독서했어요.', 'I read on the weekend.'] },
  { korean: '독일', english: 'Germany', romanization: 'do-gil', sentences: ['독일에 가고 싶어요.', 'I want to go to Germany.'] },
  { korean: '돈', english: 'money', romanization: 'don', sentences: ['돈이 필요해요.', 'I need money.'] },
  { korean: '돌아가다', english: 'return', romanization: 'do-ra-ga-da', sentences: ['집으로 돌아갔어요.', 'I returned home.'] },
  { korean: '돌아오다', english: 'come back', romanization: 'do-ra-o-da', sentences: ['곧 돌아올게요.', 'I\'ll come back soon.'] },
  { korean: '돕다', english: 'help', romanization: 'dop-da', sentences: ['친구를 도와요.', 'I help my friend.'] },
  { korean: '동네', english: 'neighborhood', romanization: 'dong-ne', sentences: ['우리 동네는 조용해요.', 'Our neighborhood is quiet.'] },
  { korean: '동대문시장', english: 'Dongdaemun Market', romanization: 'dong-dae-mun-si-jang', sentences: ['동대문시장에서 옷을 샀어요.', 'I bought clothes at Dongdaemun Market.'] },
  { korean: '동물', english: 'animal', romanization: 'dong-mul', sentences: ['동물을 좋아해요.', 'I like animals.'] },
  { korean: '동생', english: 'younger sibling', romanization: 'dong-saeng', sentences: ['동생이 둘 있어요.', 'I have two younger siblings.'] },
  { korean: '동아리', english: 'club', romanization: 'dong-a-ri', sentences: ['음악 동아리에 들어갔어요.', 'I joined the music club.'] },
  { korean: '동안', english: 'during', romanization: 'dong-an', sentences: ['방학 동안 쉬었어요.', 'I rested during vacation.'] },
  { korean: '동양', english: 'East', romanization: 'dong-yang', sentences: ['동양 문화를 공부해요.', 'I study Eastern culture.'] },
  { korean: '동전', english: 'coin', romanization: 'dong-jeon', sentences: ['동전을 모아요.', 'I collect coins.'] },
  { korean: '동쪽', english: 'east', romanization: 'dong-jjok', sentences: ['동쪽으로 가세요.', 'Go east.'] },
  { korean: '돼지', english: 'pig', romanization: 'dwae-ji', sentences: ['돼지를 키워요.', 'I raise pigs.'] },
  { korean: '돼지고기', english: 'pork', romanization: 'dwae-ji-go-gi', sentences: ['돼지고기를 먹어요.', 'I eat pork.'] },
  { korean: '되다', english: 'become', romanization: 'doe-da', sentences: ['선생님이 되고 싶어요.', 'I want to become a teacher.'] },
  { korean: '된장', english: 'soybean paste', romanization: 'doen-jang', sentences: ['된장을 넣었어요.', 'I added soybean paste.'] },
  { korean: '된장국', english: 'soybean paste soup', romanization: 'doen-jang-guk', sentences: ['된장국이 맛있어요.', 'The soybean paste soup is delicious.'] },
  { korean: '된장찌개', english: 'soybean paste stew', romanization: 'doen-jang-jji-gae', sentences: ['된장찌개를 끓였어요.', 'I made soybean paste stew.'] },
  { korean: '두', english: 'two', romanization: 'du', sentences: ['두 개 주세요.', 'Give me two please.'] },
  { korean: '두껍다', english: 'thick', romanization: 'du-kkeop-da', sentences: ['책이 두꺼워요.', 'The book is thick.'] },
  { korean: '두다', english: 'put', romanization: 'du-da', sentences: ['책상 위에 두세요.', 'Put it on the desk.'] },
  { korean: '두부', english: 'tofu', romanization: 'du-bu', sentences: ['두부를 먹어요.', 'I eat tofu.'] },
  { korean: '두부찌개', english: 'tofu stew', romanization: 'du-bu-jji-gae', sentences: ['두부찌개가 맛있어요.', 'The tofu stew is delicious.'] },
  { korean: '둘', english: 'two', romanization: 'dul', sentences: ['둘이 같이 가요.', 'The two of us go together.'] },
  { korean: '둘째', english: 'second', romanization: 'dul-jjae', sentences: ['둘째 아들이에요.', 'He\'s the second son.'] },
  { korean: '뒤', english: 'back', romanization: 'dwi', sentences: ['뒤에 앉으세요.', 'Sit in the back.'] },
  { korean: '뒤쪽', english: 'back side', romanization: 'dwi-jjok', sentences: ['뒤쪽에 있어요.', 'It\'s in the back.'] },
  { korean: '드라마', english: 'drama', romanization: 'deu-ra-ma', sentences: ['한국 드라마를 봐요.', 'I watch Korean dramas.'] },
  { korean: '드리다', english: 'give (honorific)', romanization: 'deu-ri-da', sentences: ['선물을 드렸어요.', 'I gave a gift.'] },
  { korean: '드시다', english: 'eat (honorific)', romanization: 'deu-si-da', sentences: ['맛있게 드세요.', 'Please enjoy your meal.'] },
  { korean: '듣기', english: 'listening', romanization: 'deut-gi', sentences: ['듣기 시험이 어려워요.', 'The listening test is difficult.'] },
  { korean: '듣다', english: 'listen, hear', romanization: 'deut-da', sentences: ['음악을 들어요.', 'I listen to music.'] },
  { korean: '들', english: 'field', romanization: 'deul', sentences: ['넓은 들판이에요.', 'It\'s a wide field.'] },
  { korean: '들다', english: 'hold, enter', romanization: 'deul-da', sentences: ['방에 들어가요.', 'I enter the room.'] },
  { korean: '들어가다', english: 'go in', romanization: 'deu-reo-ga-da', sentences: ['교실에 들어갔어요.', 'I went into the classroom.'] },
  { korean: '들어오다', english: 'come in', romanization: 'deu-reo-o-da', sentences: ['들어오세요.', 'Please come in.'] },
  { korean: '등', english: 'back, etc', romanization: 'deung', sentences: ['등이 아파요.', 'My back hurts.'] },
  { korean: '등산', english: 'hiking', romanization: 'deung-san', sentences: ['주말에 등산해요.', 'I go hiking on weekends.'] },
  { korean: '등산복', english: 'hiking clothes', romanization: 'deung-san-bok', sentences: ['등산복을 입었어요.', 'I wore hiking clothes.'] },
  { korean: '등산화', english: 'hiking boots', romanization: 'deung-san-hwa', sentences: ['등산화가 편해요.', 'Hiking boots are comfortable.'] },
  { korean: '디브이디', english: 'DVD', romanization: 'di-beu-i-di', sentences: ['디브이디를 봤어요.', 'I watched a DVD.'] },
  { korean: '디자인', english: 'design', romanization: 'di-ja-in', sentences: ['디자인이 예뻐요.', 'The design is pretty.'] },
  { korean: '따뜻하다', english: 'warm', romanization: 'tta-tteu-ta-da', sentences: ['커피가 따뜻해요.', 'The coffee is warm.'] },
  { korean: '따라가다', english: 'follow', romanization: 'tta-ra-ga-da', sentences: ['저를 따라오세요.', 'Follow me.'] },
  { korean: '따라오다', english: 'follow', romanization: 'tta-ra-o-da', sentences: ['강아지가 따라왔어요.', 'The puppy followed me.'] },
  { korean: '따로', english: 'separately', romanization: 'tta-ro', sentences: ['따로 앉아요.', 'We sit separately.'] },
  { korean: '따르다', english: 'follow', romanization: 'tta-reu-da', sentences: ['규칙을 따라요.', 'I follow the rules.'] },
  { korean: '딸', english: 'daughter', romanization: 'ttal', sentences: ['딸이 한 명 있어요.', 'I have one daughter.'] },
  { korean: '딸기', english: 'strawberry', romanization: 'ttal-gi', sentences: ['딸기를 좋아해요.', 'I like strawberries.'] },
  { korean: '땀', english: 'sweat', romanization: 'ttam', sentences: ['땀이 많이 나요.', 'I sweat a lot.'] },
  { korean: '때', english: 'time', romanization: 'ttae', sentences: ['그때 만났어요.', 'I met them at that time.'] },
  { korean: '때문', english: 'because of', romanization: 'ttae-mun', sentences: ['비 때문에 못 갔어요.', 'I couldn\'t go because of the rain.'] },
  { korean: '떠나다', english: 'leave', romanization: 'tteo-na-da', sentences: ['내일 떠나요.', 'I leave tomorrow.'] },
  { korean: '떠들다', english: 'make noise', romanization: 'tteo-deul-da', sentences: ['시끄럽게 떠들지 마세요.', 'Don\'t make noise.'] },
  { korean: '떡', english: 'rice cake', romanization: 'tteok', sentences: ['명절에 떡을 먹어요.', 'I eat rice cake on holidays.'] },
  { korean: '떡국', english: 'rice cake soup', romanization: 'tteok-guk', sentences: ['설날에 떡국을 먹어요.', 'I eat rice cake soup on New Year\'s.'] },
  { korean: '떡볶이', english: 'tteokbokki', romanization: 'tteok-bo-kki', sentences: ['떡볶이가 매워요.', 'Tteokbokki is spicy.'] },
  { korean: '떨어지다', english: 'fall', romanization: 'tteo-reo-ji-da', sentences: ['사과가 떨어졌어요.', 'The apple fell.'] },
  { korean: '또', english: 'again, also', romanization: 'tto', sentences: ['또 만나요.', 'See you again.'] },
  { korean: '또는', english: 'or', romanization: 'tto-neun', sentences: ['커피 또는 차를 주세요.', 'Give me coffee or tea.'] },
  { korean: '똑같다', english: 'same', romanization: 'ttok-gat-da', sentences: ['우리는 똑같아요.', 'We are the same.'] },
  { korean: '똑바로', english: 'straight', romanization: 'ttok-ba-ro', sentences: ['똑바로 가세요.', 'Go straight.'] },
  { korean: '뛰다', english: 'run', romanization: 'ttwi-da', sentences: ['운동장에서 뛰어요.', 'I run on the playground.'] },
  { korean: '뜨겁다', english: 'hot', romanization: 'tteu-geop-da', sentences: ['국이 뜨거워요.', 'The soup is hot.'] },
  { korean: '뜨다', english: 'rise, float', romanization: 'tteu-da', sentences: ['해가 떴어요.', 'The sun rose.'] },
  { korean: '뜻', english: 'meaning', romanization: 'tteut', sentences: ['단어의 뜻이 뭐예요?', 'What\'s the meaning of the word?'] },
  { korean: '라디오', english: 'radio', romanization: 'ra-di-o', sentences: ['라디오를 들어요.', 'I listen to the radio.'] },
  { korean: '라면', english: 'ramen', romanization: 'ra-myeon', sentences: ['라면을 끓였어요.', 'I cooked ramen.'] },
  { korean: '러시아', english: 'Russia', romanization: 'reo-si-a', sentences: ['러시아어를 배워요.', 'I learn Russian.'] },
  { korean: '로션', english: 'lotion', romanization: 'ro-syeon', sentences: ['로션을 발라요.', 'I apply lotion.'] },
  { korean: '마늘', english: 'garlic', romanization: 'ma-neul', sentences: ['마늘을 많이 넣었어요.', 'I added a lot of garlic.'] },
  { korean: '마르다', english: 'dry', romanization: 'ma-reu-da', sentences: ['옷이 말랐어요.', 'The clothes dried.'] },
  { korean: '마리', english: 'animal counter', romanization: 'ma-ri', sentences: ['고양이 두 마리가 있어요.', 'There are two cats.'] },
  { korean: '마시다', english: 'drink', romanization: 'ma-si-da', sentences: ['물을 마셔요.', 'I drink water.'] },
  { korean: '마음', english: 'heart, mind', romanization: 'ma-eum', sentences: ['마음이 편해요.', 'My mind is at ease.'] },
  { korean: '마지막', english: 'last', romanization: 'ma-ji-mak', sentences: ['마지막 기회예요.', 'It\'s the last chance.'] },
  { korean: '마치다', english: 'finish', romanization: 'ma-chi-da', sentences: ['일을 마쳤어요.', 'I finished work.'] },
  { korean: '마흔', english: '40', romanization: 'ma-heun', sentences: ['마흔 살이에요.', 'I\'m 40 years old.'] },
  { korean: '막히다', english: 'be blocked', romanization: 'ma-ki-da', sentences: ['길이 막혔어요.', 'The road is blocked.'] },
  { korean: '만', english: 'only, 10,000', romanization: 'man', sentences: ['만 원이에요.', 'It\'s 10,000 won.'] },
  { korean: '만나다', english: 'meet', romanization: 'man-na-da', sentences: ['친구를 만났어요.', 'I met a friend.'] },
  { korean: '만두', english: 'dumpling', romanization: 'man-du', sentences: ['만두를 쪘어요.', 'I steamed dumplings.'] },
  { korean: '만들다', english: 'make', romanization: 'man-deul-da', sentences: ['케이크를 만들었어요.', 'I made a cake.'] },
  { korean: '만일', english: 'if', romanization: 'ma-nil', sentences: ['만일 비가 오면 집에 있을게요.', 'If it rains, I\'ll stay home.'] },
  { korean: '만지다', english: 'touch', romanization: 'man-ji-da', sentences: ['만지지 마세요.', 'Don\'t touch it.'] },
  { korean: '만화', english: 'comic', romanization: 'man-hwa', sentences: ['만화책을 읽어요.', 'I read comic books.'] },
  { korean: '많다', english: 'many', romanization: 'man-ta', sentences: ['사람이 많아요.', 'There are many people.'] },
  { korean: '많이', english: 'a lot', romanization: 'ma-ni', sentences: ['많이 먹었어요.', 'I ate a lot.'] },
  { korean: '말', english: 'word, horse', romanization: 'mal', sentences: ['한국말을 배워요.', 'I learn Korean.'] },
  { korean: '말씀', english: 'words (honorific)', romanization: 'mal-sseum', sentences: ['말씀 감사합니다.', 'Thank you for your words.'] },
  { korean: '말씀하다', english: 'speak (honorific)', romanization: 'mal-sseum-ha-da', sentences: ['천천히 말씀해 주세요.', 'Please speak slowly.'] },
  { korean: '말하기', english: 'speaking', romanization: 'ma-ra-gi', sentences: ['말하기 연습을 해요.', 'I practice speaking.'] },
  { korean: '말하다', english: 'speak', romanization: 'ma-ra-da', sentences: ['한국어로 말해요.', 'I speak in Korean.'] },
  { korean: '맑다', english: 'clear', romanization: 'malk-da', sentences: ['하늘이 맑아요.', 'The sky is clear.'] },
  { korean: '맛', english: 'taste', romanization: 'mat', sentences: ['맛이 좋아요.', 'It tastes good.'] },
  { korean: '맛없다', english: 'not delicious', romanization: 'ma-deop-da', sentences: ['이 음식은 맛없어요.', 'This food is not delicious.'] },
  { korean: '맛있다', english: 'delicious', romanization: 'ma-sit-da', sentences: ['정말 맛있어요!', 'It\'s really delicious!'] },
  { korean: '맞다', english: 'correct, fit', romanization: 'mat-da', sentences: ['답이 맞아요.', 'The answer is correct.'] },
  { korean: '맞습니다', english: 'that\'s right', romanization: 'mat-seum-ni-da', sentences: ['네, 맞습니다.', 'Yes, that\'s correct.'] },
  { korean: '맞아요', english: 'that\'s right', romanization: 'ma-ja-yo', sentences: ['맞아요, 그거예요.', 'That\'s right, that\'s it.'] },
  { korean: '맞은편', english: 'opposite side', romanization: 'ma-jeun-pyeon', sentences: ['맞은편에 은행이 있어요.', 'There\'s a bank on the opposite side.'] },
  { korean: '매다', english: 'tie', romanization: 'mae-da', sentences: ['넥타이를 매요.', 'I tie a necktie.'] },
  { korean: '매우', english: 'very', romanization: 'mae-u', sentences: ['매우 기뻐요.', 'I\'m very happy.'] },
  { korean: '매일', english: 'every day', romanization: 'mae-il', sentences: ['매일 운동해요.', 'I exercise every day.'] },
  { korean: '매주', english: 'every week', romanization: 'mae-ju', sentences: ['매주 월요일에 회의해요.', 'We have meetings every Monday.'] },
  { korean: '맥주', english: 'beer', romanization: 'maek-ju', sentences: ['맥주 한 잔 주세요.', 'One beer, please.'] },
  { korean: '맵다', english: 'spicy', romanization: 'maep-da', sentences: ['김치가 매워요.', 'Kimchi is spicy.'] },
  { korean: '머리', english: 'head, hair', romanization: 'meo-ri', sentences: ['머리가 아파요.', 'My head hurts.'] },
  { korean: '먹다', english: 'eat', romanization: 'meok-da', sentences: ['아침을 먹었어요.', 'I ate breakfast.'] },
  { korean: '먼저', english: 'first', romanization: 'meon-jeo', sentences: ['먼저 드세요.', 'Please eat first.'] },
  { korean: '멀다', english: 'far', romanization: 'meol-da', sentences: ['학교가 멀어요.', 'School is far.'] },
  { korean: '멋있다', english: 'cool, nice', romanization: 'meo-sit-da', sentences: ['정말 멋있어요!', 'It\'s really cool!'] },
  { korean: '메뉴', english: 'menu', romanization: 'me-nyu', sentences: ['메뉴판을 보여 주세요.', 'Please show me the menu.'] },
  { korean: '메다', english: 'carry on shoulder', romanization: 'me-da', sentences: ['가방을 메고 가요.', 'I carry the bag on my shoulder.'] },
  { korean: '메모', english: 'memo', romanization: 'me-mo', sentences: ['메모를 했어요.', 'I made a memo.'] },
  { korean: '메시지', english: 'message', romanization: 'me-si-ji', sentences: ['메시지를 보냈어요.', 'I sent a message.'] },
  { korean: '멕시코', english: 'Mexico', romanization: 'mek-si-ko', sentences: ['멕시코 음식을 좋아해요.', 'I like Mexican food.'] },
  { korean: '며칠', english: 'what date, few days', romanization: 'myeo-chil', sentences: ['며칠 동안 있었어요?', 'How many days were you there?'] },
  { korean: '면도', english: 'shaving', romanization: 'myeon-do', sentences: ['아침에 면도해요.', 'I shave in the morning.'] },
  { korean: '명', english: 'person counter', romanization: 'myeong', sentences: ['다섯 명이에요.', 'There are five people.'] },
  { korean: '명절', english: 'holiday', romanization: 'myeong-jeol', sentences: ['명절에 가족을 만나요.', 'I meet family during holidays.'] },
  { korean: '몇', english: 'how many', romanization: 'myeot', sentences: ['몇 개 필요해요?', 'How many do you need?'] },
  { korean: '모두', english: 'all, everyone', romanization: 'mo-du', sentences: ['모두 왔어요.', 'Everyone came.'] },
  { korean: '모레', english: 'day after tomorrow', romanization: 'mo-re', sentences: ['모레 만나요.', 'Let\'s meet the day after tomorrow.'] },
  { korean: '모르겠습니다', english: 'I don\'t know', romanization: 'mo-reu-get-seum-ni-da', sentences: ['죄송하지만 모르겠습니다.', 'I\'m sorry but I don\'t know.'] },
  { korean: '모르다', english: 'not know', romanization: 'mo-reu-da', sentences: ['이름을 몰라요.', 'I don\'t know the name.'] },
  { korean: '모시다', english: 'serve (honorific)', romanization: 'mo-si-da', sentences: ['부모님을 모셔요.', 'I serve my parents.'] },
  { korean: '모양', english: 'shape', romanization: 'mo-yang', sentences: ['동그란 모양이에요.', 'It\'s a round shape.'] },
  { korean: '모으다', english: 'collect', romanization: 'mo-eu-da', sentences: ['우표를 모아요.', 'I collect stamps.'] },
  { korean: '모이다', english: 'gather', romanization: 'mo-i-da', sentences: ['친구들이 모였어요.', 'Friends gathered.'] },
  { korean: '모임', english: 'meeting', romanization: 'mo-im', sentences: ['내일 모임이 있어요.', 'There\'s a meeting tomorrow.'] },
  { korean: '모자', english: 'hat', romanization: 'mo-ja', sentences: ['모자를 썼어요.', 'I wore a hat.'] },
  { korean: '목', english: 'neck, throat', romanization: 'mok', sentences: ['목이 아파요.', 'My throat hurts.'] },
  { korean: '목걸이', english: 'necklace', romanization: 'mok-geo-ri', sentences: ['예쁜 목걸이예요.', 'It\'s a pretty necklace.'] },
  { korean: '목소리', english: 'voice', romanization: 'mok-so-ri', sentences: ['목소리가 좋아요.', 'You have a nice voice.'] },
  { korean: '목요일', english: 'Thursday', romanization: 'mo-gyo-il', sentences: ['목요일에 만나요.', 'Let\'s meet on Thursday.'] },
  { korean: '목욕', english: 'bath', romanization: 'mo-gyok', sentences: ['목욕했어요.', 'I took a bath.'] },
  { korean: '목욕하다', english: 'take a bath', romanization: 'mo-gyo-ka-da', sentences: ['매일 목욕해요.', 'I bathe every day.'] },
  { korean: '목적', english: 'purpose', romanization: 'mok-jeok', sentences: ['여행 목적이 뭐예요?', 'What\'s the purpose of your trip?'] },
  { korean: '몸', english: 'body', romanization: 'mom', sentences: ['몸이 안 좋아요.', 'I don\'t feel well.'] },
  { korean: '몸살', english: 'body aches', romanization: 'mom-sal', sentences: ['몸살이 났어요.', 'I have body aches.'] },
  { korean: '못하다', english: 'cannot', romanization: 'mo-ta-da', sentences: ['수영을 못해요.', 'I can\'t swim.'] },
  { korean: '몽골', english: 'Mongolia', romanization: 'mong-gol', sentences: ['몽골 여행을 갔어요.', 'I traveled to Mongolia.'] },
  { korean: '무', english: 'radish', romanization: 'mu', sentences: ['무를 썰었어요.', 'I sliced radish.'] },
  { korean: '무겁다', english: 'heavy', romanization: 'mu-geop-da', sentences: ['짐이 무거워요.', 'The luggage is heavy.'] },
  { korean: '무궁화', english: 'rose of sharon', romanization: 'mu-gung-hwa', sentences: ['무궁화는 한국 꽃이에요.', 'Rose of sharon is Korea\'s flower.'] },
  { korean: '무료', english: 'free', romanization: 'mu-ryo', sentences: ['입장이 무료예요.', 'Admission is free.'] },
  { korean: '무릎', english: 'knee', romanization: 'mu-reup', sentences: ['무릎이 아파요.', 'My knee hurts.'] },
  { korean: '무리', english: 'group, unreasonable', romanization: 'mu-ri', sentences: ['무리하지 마세요.', 'Don\'t overdo it.'] },
  { korean: '무섭다', english: 'scary', romanization: 'mu-seop-da', sentences: ['귀신이 무서워요.', 'Ghosts are scary.'] },
  { korean: '무슨', english: 'what', romanization: 'mu-seun', sentences: ['무슨 일이에요?', 'What\'s the matter?'] },
  { korean: '무엇', english: 'what', romanization: 'mu-eot', sentences: ['무엇을 원해요?', 'What do you want?'] },
  { korean: '무엇이', english: 'what (subject)', romanization: 'mu-eo-si', sentences: ['무엇이 필요해요?', 'What do you need?'] },
  { korean: '무역', english: 'trade', romanization: 'mu-yeok', sentences: ['국제 무역을 해요.', 'I do international trade.'] },
  { korean: '무용', english: 'dance', romanization: 'mu-yong', sentences: ['무용을 배워요.', 'I learn dance.'] },
  { korean: '무척', english: 'very', romanization: 'mu-cheok', sentences: ['무척 기뻐요.', 'I\'m very happy.'] },
  { korean: '문', english: 'door', romanization: 'mun', sentences: ['문을 열어 주세요.', 'Please open the door.'] },
  { korean: '문구점', english: 'stationery store', romanization: 'mun-gu-jeom', sentences: ['문구점에서 펜을 샀어요.', 'I bought a pen at the stationery store.'] },
  { korean: '문장', english: 'sentence', romanization: 'mun-jang', sentences: ['문장을 만들어요.', 'I make sentences.'] },
  { korean: '문제', english: 'problem', romanization: 'mun-je', sentences: ['어려운 문제예요.', 'It\'s a difficult problem.'] },
  { korean: '문화', english: 'culture', romanization: 'mun-hwa', sentences: ['한국 문화가 흥미로워요.', 'Korean culture is interesting.'] },
  { korean: '묻다', english: 'ask', romanization: 'mut-da', sentences: ['질문을 물었어요.', 'I asked a question.'] },
  { korean: '물', english: 'water', romanization: 'mul', sentences: ['물을 마셔요.', 'I drink water.'] },
  { korean: '물건', english: 'thing, item', romanization: 'mul-geon', sentences: ['물건을 샀어요.', 'I bought things.'] },
  { korean: '물론', english: 'of course', romanization: 'mul-lon', sentences: ['물론이죠!', 'Of course!'] },
  { korean: '물어보다', english: 'ask', romanization: 'mu-reo-bo-da', sentences: ['길을 물어봤어요.', 'I asked for directions.'] },
  { korean: '뭐', english: 'what', romanization: 'mwo', sentences: ['뭐 해요?', 'What are you doing?'] },
  { korean: '미국', english: 'USA', romanization: 'mi-guk', sentences: ['미국에서 왔어요.', 'I came from the USA.'] },
  { korean: '미래', english: 'future', romanization: 'mi-rae', sentences: ['미래가 기대돼요.', 'I look forward to the future.'] },
  { korean: '미리', english: 'in advance', romanization: 'mi-ri', sentences: ['미리 준비하세요.', 'Prepare in advance.'] },
  { korean: '미술', english: 'art', romanization: 'mi-sul', sentences: ['미술을 좋아해요.', 'I like art.'] },
  { korean: '미술관', english: 'art museum', romanization: 'mi-sul-gwan', sentences: ['미술관에 갔어요.', 'I went to the art museum.'] },
  { korean: '미안하다', english: 'sorry', romanization: 'mi-an-ha-da', sentences: ['정말 미안해요.', 'I\'m really sorry.'] },
  { korean: '미안합니다', english: 'I\'m sorry', romanization: 'mi-an-ham-ni-da', sentences: ['늦어서 미안합니다.', 'I\'m sorry for being late.'] },
  { korean: '미용실', english: 'beauty salon', romanization: 'mi-yong-sil', sentences: ['미용실에서 머리를 잘랐어요.', 'I cut my hair at the salon.'] },
  { korean: '미터', english: 'meter', romanization: 'mi-teo', sentences: ['10미터예요.', 'It\'s 10 meters.'] },
  { korean: '민속촌', english: 'folk village', romanization: 'min-sok-chon', sentences: ['민속촌을 구경했어요.', 'I toured the folk village.'] },
  { korean: '밀가루', english: 'flour', romanization: 'mil-ga-ru', sentences: ['밀가루로 빵을 만들어요.', 'I make bread with flour.'] },
  { korean: '밀리다', english: 'be pushed', romanization: 'mil-li-da', sentences: ['사람에게 밀렸어요.', 'I was pushed by people.'] },
  { korean: '밑', english: 'bottom', romanization: 'mit', sentences: ['책상 밑에 있어요.', 'It\'s under the desk.'] },
  { korean: '바꾸다', english: 'change', romanization: 'ba-kku-da', sentences: ['돈을 바꿨어요.', 'I exchanged money.'] },
  { korean: '바뀌다', english: 'be changed', romanization: 'ba-kkwi-da', sentences: ['계획이 바뀌었어요.', 'The plan changed.'] },
  { korean: '바나나', english: 'banana', romanization: 'ba-na-na', sentences: ['바나나를 먹어요.', 'I eat bananas.'] },
  { korean: '바다', english: 'sea', romanization: 'ba-da', sentences: ['바다가 아름다워요.', 'The sea is beautiful.'] },
  { korean: '바닷가', english: 'beach', romanization: 'ba-dat-ga', sentences: ['바닷가에서 놀았어요.', 'I played at the beach.'] },
  { korean: '바라다', english: 'hope', romanization: 'ba-ra-da', sentences: ['행복을 바라요.', 'I hope for happiness.'] },
  { korean: '바람', english: 'wind', romanization: 'ba-ram', sentences: ['바람이 불어요.', 'The wind is blowing.'] },
  { korean: '바로', english: 'right away', romanization: 'ba-ro', sentences: ['바로 갈게요.', 'I\'ll go right away.'] },
  { korean: '바르다', english: 'right, apply', romanization: 'ba-reu-da', sentences: ['크림을 발라요.', 'I apply cream.'] },
  { korean: '바쁘다', english: 'busy', romanization: 'ba-ppeu-da', sentences: ['요즘 바빠요.', 'I\'m busy these days.'] },
  { korean: '바지', english: 'pants', romanization: 'ba-ji', sentences: ['바지를 입어요.', 'I wear pants.'] },
  { korean: '바퀴', english: 'wheel', romanization: 'ba-kwi', sentences: ['자동차 바퀴가 고장났어요.', 'The car wheel is broken.'] },
  { korean: '바탕', english: 'basis', romanization: 'ba-tang', sentences: ['바탕 화면이에요.', 'It\'s the desktop.'] },
  { korean: '박물관', english: 'museum', romanization: 'bak-mul-gwan', sentences: ['박물관에 갔어요.', 'I went to the museum.'] },
  { korean: '박스', english: 'box', romanization: 'bak-seu', sentences: ['박스에 넣었어요.', 'I put it in the box.'] },
  { korean: '반', english: 'half, class', romanization: 'ban', sentences: ['반이 시작됐어요.', 'The class has started.'] },
  { korean: '반갑다', english: 'nice to meet you', romanization: 'ban-gap-da', sentences: ['만나서 반가워요.', 'Nice to meet you.'] },
  { korean: '반대하다', english: 'oppose', romanization: 'ban-dae-ha-da', sentences: ['그 의견에 반대해요.', 'I oppose that opinion.'] },
  { korean: '반드시', english: 'definitely', romanization: 'ban-deu-si', sentences: ['반드시 성공할 거예요.', 'I will definitely succeed.'] },
  { korean: '반복하다', english: 'repeat', romanization: 'ban-bok-ha-da', sentences: ['연습을 반복해요.', 'I repeat the practice.'] },
    { korean: '반짝', english: 'sparkle', romanization: 'ban-jjak', sentences: ['별이 반짝여요.', 'The stars are sparkling.'] },
  { korean: '반지', english: 'ring', romanization: 'ban-ji', sentences: ['반지를 샀어요.', 'I bought a ring.'] },
  { korean: '발', english: 'foot, leg', romanization: 'bal', sentences: ['발이 아파요.', 'My foot hurts.'] },
  { korean: '발견하다', english: 'discover', romanization: 'bal-gyeon-ha-da', sentences: ['새로운 것을 발견했어요.', 'I discovered something new.'] },
  { korean: '발달하다', english: 'develop', romanization: 'bal-dal-ha-da', sentences: ['기술이 발달했어요.', 'Technology has developed.'] },
  { korean: '발레', english: 'ballet', romanization: 'bal-le', sentences: ['발레를 배워요.', 'I learn ballet.'] },
  { korean: '발음', english: 'pronunciation', romanization: 'bal-eum', sentences: ['발음이 좋아요.', 'Your pronunciation is good.'] },
  { korean: '발음하다', english: 'pronounce', romanization: 'bal-eum-ha-da', sentences: ['단어를 발음해요.', 'I pronounce the word.'] },
  { korean: '발자국', english: 'footprint', romanization: 'bal-ja-guk', sentences: ['발자국이 보여요.', 'I see footprints.'] },
  { korean: '밝다', english: 'bright', romanization: 'bak-da', sentences: ['방이 밝아요.', 'The room is bright.'] },
  { korean: '밝히다', english: 'reveal', romanization: 'bak-hi-da', sentences: ['비밀을 밝혔어요.', 'I revealed the secret.'] },
  { korean: '밤', english: 'night, chestnut', romanization: 'bam', sentences: ['밤에 별이 보여요.', 'I see stars at night.'] },
  { korean: '밤새', english: 'all night', romanization: 'bam-sae', sentences: ['밤새 공부했어요.', 'I studied all night.'] },
  { korean: '밤하늘', english: 'night sky', romanization: 'bam-ha-neul', sentences: ['밤하늘이 아름다워요.', 'The night sky is beautiful.'] },
  { korean: '밥', english: 'rice, meal', romanization: 'bap', sentences: ['밥을 먹었어요.', 'I ate a meal.'] },
  { korean: '밥솥', english: 'rice cooker', romanization: 'bap-sot', sentences: ['밥솥에 밥을 했어요.', 'I cooked rice in the rice cooker.'] },
  { korean: '밥집', english: 'restaurant', romanization: 'bap-jip', sentences: ['밥집에서 저녁을 먹었어요.', 'I had dinner at the restaurant.'] },
  { korean: '밥통', english: 'rice container', romanization: 'bap-tong', sentences: ['밥통에 밥이 있어요.', 'There\'s rice in the container.'] },
  { korean: '밥하다', english: 'cook rice', romanization: 'bap-ha-da', sentences: ['오늘 밥했어요.', 'I cooked rice today.'] },
  { korean: '방', english: 'room', romanization: 'bang', sentences: ['방이 깨끗해요.', 'The room is clean.'] },
  { korean: '방금', english: 'just now', romanization: 'bang-geum', sentences: ['방금 도착했어요.', 'I just arrived.'] },
  { korean: '방문하다', english: 'visit', romanization: 'bang-mun-ha-da', sentences: ['친구 집을 방문했어요.', 'I visited a friend\'s house.'] },
  { korean: '방송', english: 'broadcast', romanization: 'bang-song', sentences: ['방송을 봐요.', 'I watch the broadcast.'] },
  { korean: '방송국', english: 'broadcasting station', romanization: 'bang-song-guk', sentences: ['방송국에서 일해요.', 'I work at a broadcasting station.'] },
  { korean: '방송하다', english: 'broadcast', romanization: 'bang-song-ha-da', sentences: ['뉴스를 방송해요.', 'I broadcast the news.'] },
  { korean: '방학', english: 'vacation (school)', romanization: 'bang-hak', sentences: ['방학 동안 여행할 거예요.', 'I will travel during the vacation.'] },
  { korean: '배', english: 'stomach, boat, pear', romanization: 'bae', sentences: ['배가 고파요.', 'I\'m hungry.'] },
  { korean: '배달하다', english: 'deliver', romanization: 'bae-dal-ha-da', sentences: ['음식을 배달했어요.', 'I delivered food.'] },
  { korean: '배우다', english: 'learn', romanization: 'bae-u-da', sentences: ['한국어를 배워요.', 'I learn Korean.'] },
  { korean: '배우자', english: 'spouse', romanization: 'bae-u-ja', sentences: ['배우자를 만났어요.', 'I met my spouse.'] },
  { korean: '배우지다', english: 'become plump', romanization: 'bae-u-ji-da', sentences: ['아기가 배부르니까 배가 부풀었어요.', 'The baby is full, so the stomach is swollen.'] },
  { korean: '배추', english: 'napa cabbage', romanization: 'bae-chu', sentences: ['배추로 김치를 만들어요.', 'I make kimchi with napa cabbage.'] },
  { korean: '백', english: '100', romanization: 'baek', sentences: ['백 원이에요.', 'It\'s 100 won.'] },
  { korean: '백화점', english: 'department store', romanization: 'baek-hwa-jeom', sentences: ['백화점에서 쇼핑했어요.', 'I shopped at the department store.'] },
  { korean: '버스', english: 'bus', romanization: 'beo-seu', sentences: ['버스를 타요.', 'I take the bus.'] },
  { korean: '버섯', english: 'mushroom', romanization: 'beo-seot', sentences: ['버섯을 볶았어요.', 'I stir-fried mushrooms.'] },
  { korean: '버티다', english: 'endure', romanization: 'beo-ti-da', sentences: ['힘든 상황을 버텼어요.', 'I endured a difficult situation.'] },
  { korean: '번', english: 'time (counter)', romanization: 'beon', sentences: ['한 번 더 해요.', 'Let\'s do it one more time.'] },
  { korean: '번역하다', english: 'translate', romanization: 'beon-yeok-ha-da', sentences: ['문서를 번역했어요.', 'I translated the document.'] },
  { korean: '번지', english: 'house number', romanization: 'beon-ji', sentences: ['우리 집 번지는 123이에요.', 'Our house number is 123.'] },
  { korean: '벌', english: 'bee, punishment', romanization: 'beol', sentences: ['벌이 날아와요.', 'A bee is flying.'] },
  { korean: '벌다', english: 'earn', romanization: 'beol-da', sentences: ['돈을 벌어요.', 'I earn money.'] },
  { korean: '벌써', english: 'already', romanization: 'beol-sseo', sentences: ['벌써 시간이 이렇게 됐어요?', 'Has it already become this late?'] },
  { korean: '벌어지다', english: 'happen', romanization: 'beol-eo-ji-da', sentences: ['큰 일이 벌어졌어요.', 'A big event happened.'] },
  { korean: '벌이다', english: 'start, set up', romanization: 'beol-i-da', sentences: ['행사를 벌였어요.', 'I set up an event.'] },
  { korean: '범죄', english: 'crime', romanization: 'beom-joi', sentences: ['범죄를 저질렀어요.', 'I committed a crime.'] },
  { korean: '법', english: 'law', romanization: 'beop', sentences: ['법을 지켜야 해요.', 'You must follow the law.'] },
  { korean: '법원', english: 'court', romanization: 'beop-won', sentences: ['법원에서 일해요.', 'I work at the court.'] },
  { korean: '법적', english: 'legal', romanization: 'beop-jeok', sentences: ['법적 문제가 있어요.', 'There\'s a legal issue.'] },
  { korean: '베개', english: 'pillow', romanization: 'be-gae', sentences: ['베개가 편해요.', 'The pillow is comfortable.'] },
  { korean: '베이징', english: 'Beijing', romanization: 'bei-jing', sentences: ['베이징에 가봤어요.', 'I have been to Beijing.'] },
  { korean: '베트남', english: 'Vietnam', romanization: 'be-teu-nam', sentences: ['베트남 음식이 맛있어요.', 'Vietnamese food is delicious.'] },
  { korean: '베풀다', english: 'bestow', romanization: 'be-ppeul-da', sentences: ['친절을 베풀어요.', 'I bestow kindness.'] },
  { korean: '베이비', english: 'baby', romanization: 'be-i-bi', sentences: ['베이비 옷을 샀어요.', 'I bought baby clothes.'] },
   { korean: '벗다', english: 'take off', romanization: 'beot-da', sentences: ['신발을 벗어요.', 'I take off my shoes.'] },
  { korean: '벼락', english: 'lightning', romanization: 'byeo-rak', sentences: ['벼락이 쳤어요.', 'Lightning struck.'] },
  { korean: '변하다', english: 'change', romanization: 'byeon-ha-da', sentences: ['날씨가 변했어요.', 'The weather changed.'] },
  { korean: '변호사', english: 'lawyer', romanization: 'byeon-ho-sa', sentences: ['변호사로 일해요.', 'I work as a lawyer.'] },
  { korean: '별', english: 'star', romanization: 'byeol', sentences: ['밤하늘에 별이 보여요.', 'I see stars in the night sky.'] },
  { korean: '별명', english: 'nickname', romanization: 'byeol-myeong', sentences: ['제 별명은 "별"이에요.', 'My nickname is "Star".'] },
  { korean: '별일', english: 'special event', romanization: 'byeol-il', sentences: ['별일 없어요.', 'Nothing special is happening.'] },
  { korean: '보라색', english: 'purple', romanization: 'bo-ra-saek', sentences: ['보라색 꽃이에요.', 'It\'s a purple flower.'] },
  { korean: '보리차', english: 'barley tea', romanization: 'bo-ri-cha', sentences: ['보리차를 마셔요.', 'I drink barley tea.'] },
  { korean: '보름', english: 'full moon, 15 days', romanization: 'bo-reum', sentences: ['보름달이 보여요.', 'I see the full moon.'] },
  { korean: '보스턴', english: 'Boston', romanization: 'bo-seu-teon', sentences: ['보스턴에 가봤어요.', 'I have been to Boston.'] },
  { korean: '보안', english: 'security', romanization: 'bo-an', sentences: ['보안이 강화됐어요.', 'Security has been strengthened.'] },
  { korean: '보이다', english: 'be visible', romanization: 'bo-i-da', sentences: ['산이 보여요.', 'I see the mountain.'] },
  { korean: '보통', english: 'usually', romanization: 'bo-tong', sentences: ['보통 아침에 운동해요.', 'I usually exercise in the morning.'] },
  { korean: '복사하다', english: 'copy', romanization: 'bok-sa-ha-da', sentences: ['문서를 복사했어요.', 'I copied the document.'] },
  { korean: '복잡하다', english: 'complicated, crowded', romanization: 'bok-jap-ha-da', sentences: ['복잡한 일이에요.', 'It\'s a complicated matter.'] },

  // TODO: Add remaining 1,661 TOPIK I words from your PDF
];

// TOPIK II Words - Intermediate (Add all 2,662 from your PDF)
export const topikIIWords = [
  { korean: '가계부', english: 'household account book', romanization: 'ga-gye-bu', sentences: ['가계부를 정리해요.', 'I organize the account book.'] },
  { korean: '가꾸다', english: 'to cultivate', romanization: 'ga-kku-da', sentences: ['정원을 가꿔요.', 'I cultivate the garden.'] },
  { korean: '가능하다', english: 'to be possible', romanization: 'ga-neung-ha-da', sentences: ['모든 것이 가능해요.', 'Everything is possible.'] },
  { korean: '가득', english: 'full', romanization: 'ga-deuk', sentences: ['컵이 가득 찼어요.', 'The cup is full.'] },
  { korean: '가리키다', english: 'to indicate', romanization: 'ga-ri-ki-da', sentences: ['방향을 가리켜요.', 'I point the direction.'] },
  // TODO: Add remaining 2,657 TOPIK II words from your PDF
];

export const allWords = [...topikIWords, ...topikIIWords];

export const ranks = [
  { name: '초보자', min: 0, max: 49, color: 'gray', level: 'TOPIK I' },
  { name: '학습자', min: 50, max: 149, color: 'blue', level: 'TOPIK I' },
  { name: '숙련자', min: 150, max: 299, color: 'cyan', level: 'TOPIK I' },
  { name: '고급자', min: 300, max: 499, color: 'green', level: 'TOPIK I→II' },
  { name: '전문가', min: 500, max: 999, color: 'purple', level: 'TOPIK II' },
  { name: '마스터', min: 1000, max: 1999, color: 'pink', level: 'TOPIK II' },
  { name: '그랜드마스터', min: 2000, max: 2999, color: 'orange', level: 'TOPIK II' },
  { name: '전설', min: 3000, max: Infinity, color: 'yellow', level: 'Complete' },
];